import { option, DyanamicObj } from './types';

export const optionsList: option[] = [
  { label: 'JSON', value: 'json' },
  { label: 'HTML', value: 'html' },
  { label: 'Javascript', value: 'javascript' },
  { label: 'XML', value: 'xml' },
  { label: 'Plain Text', value: 'plaintext' },
];

export const variableList: DyanamicObj[] = [
  {
    _id: 'PARAMETER9cb087a0-745d-4bca-a08e-6d006b77f46b',
    name: 'asdfgh',
    type: 'Array',
    createdBy: 'USR18246',
    modifiedBy: 'USR18246',
    createdByUname: 'Md Imran',
    modifiedByUname: 'Md Imran',
    createdOn: '24 Feb 2025 05:10 PM',
    modifiedOn: '24 Feb 2025 05:10 PM',
  },
  {
    createdBy: 'USR18246',
    modifiedBy: 'USR18246',
    createdByUname: 'Md Imran',
    modifiedByUname: 'Md Imran',
    createdOn: '24 Feb 2025 05:11 PM',
    modifiedOn: '24 Feb 2025 05:11 PM',
    state: 'APPROVED',
    version: '1.0',
    id: 'VARa03a2439-a5fa-4077-8596-b70f4b0ec866',
    name: 'wedrftg',
    value: '',
    encrypt: false,
    returningStep: '',
    type: 'LOCAL',
    projectId: 'PJT1032',
    parentVariableType: 'STEPGROUP',
    parentVariableId: 'LIBf2bfa8a5-5630-4c08-8dbf-66e3dfdcd6c7',
    subParentVariableId: 'STP_GRP6dbcb0f1-2264-4736-a245-8db2d3a779d5',
    isSystemVariable: false,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    createdBy: 'USR1428',
    modifiedBy: '--',
    createdByUname: 'Mohammed Saqeb',
    modifiedByUname: '--',
    createdOn: '01 Apr 2022 11:32 AM',
    modifiedOn: '--',
    state: 'NEW',
    ver: 1,
    id: 'VAR1226',
    name: 'Capability',
    value: '',
    encrypt: false,
    type: 'GLOBAL',
    projectId: 'PJT1022',
    isSystemVariable: true,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    createdBy: 'USR18218',
    modifiedBy: 'USR18218',
    createdByUname: 'Ubaid',
    modifiedByUname: 'Ubaid',
    createdOn: '11 Mar 2025 03:22 PM',
    modifiedOn: '11 Mar 2025 03:22 PM',
    state: 'APPROVED',
    version: '1.0',
    id: 'VARa85c6280-e225-4a5d-b7d9-90f45a7ae557',
    name: 'asdfghn',
    value: 'tyjuhytret',
    encrypt: false,
    returningStep: '',
    type: 'LOCAL',
    projectId: 'PJT1020',
    parentVariableType: 'STEPGROUP',
    parentVariableId: 'LIB33e9a340-6b6b-4172-ab30-990d9c3213c5',
    subParentVariableId: 'STP_GRPf0abf305-6e36-4843-8023-67b05fc2ece8',
    isSystemVariable: false,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    createdBy: 'USR1428',
    modifiedBy: '--',
    createdByUname: 'Mohammed Saqeb',
    modifiedByUname: '--',
    createdOn: '01 Apr 2022 11:32 AM',
    modifiedOn: '--',
    state: 'NEW',
    ver: 1,
    id: 'VAR1227',
    name: 'BrowserCapbility',
    value: '',
    encrypt: false,
    type: 'GLOBAL',
    projectId: 'PJT1022',
    isSystemVariable: true,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    createdBy: 'USR1428',
    modifiedBy: '--',
    createdByUname: 'Mohammed Saqeb',
    modifiedByUname: '--',
    createdOn: '01 Apr 2022 11:32 AM',
    modifiedOn: '--',
    state: 'NEW',
    ver: 1,
    id: 'VAR1228',
    name: 'HubURL',
    value: 'http://localhost:4444/wd/hub',
    encrypt: false,
    type: 'GLOBAL',
    projectId: 'PJT1022',
    isSystemVariable: true,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    createdBy: 'USR18218',
    modifiedBy: 'USR18218',
    createdByUname: 'Ubaid',
    modifiedByUname: 'Ubaid',
    createdOn: '11 Mar 2025 04:16 PM',
    modifiedOn: '11 Mar 2025 04:16 PM',
    state: 'APPROVED',
    version: '1.0',
    id: 'VAR9fbe82d4-3d41-462f-badc-4876875336d7',
    name: 'sadfvbasdfgdfg',
    value: 'sadfvbasdfgdfg',
    encrypt: false,
    returningStep: '',
    type: 'LOCAL',
    projectId: 'PJT1020',
    parentVariableType: 'STEPGROUP',
    parentVariableId: 'LIB33e9a340-6b6b-4172-ab30-990d9c3213c5',
    subParentVariableId: 'STP_GRPf0abf305-6e36-4843-8023-67b05fc2ece8',
    isSystemVariable: false,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    createdBy: 'USR1428',
    modifiedBy: '--',
    createdByUname: 'Mohammed Saqeb',
    modifiedByUname: '--',
    createdOn: '01 Apr 2022 11:32 AM',
    modifiedOn: '--',
    state: 'NEW',
    ver: 1,
    id: 'VAR1229',
    name: 'Capability2',
    value: 'trst',
    encrypt: false,
    type: 'LOCAL',
    projectId: 'PJT1022',
    isSystemVariable: true,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    createdBy: 'USR1428',
    modifiedBy: 'USR41096',
    createdByUname: 'Mohammed Saqeb',
    modifiedByUname: 'Saqeb',
    createdOn: '01 Apr 2022 11:32 AM',
    modifiedOn: '30 Jun 2023 06:44 PM',
    state: 'NEW',
    ver: 1,
    id: 'VAR1225',
    name: 'browser',
    value: 'Google Chrome',
    encrypt: false,
    type: 'PROJECT_ENVIRONMENT',
    projectId: 'PJT1022',
    isSystemVariable: false,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    "refId": "DP_VAR3bbde401-a029-4547-b37a-11236b5b915c",
    "parentId": "MODa356ece4-1076-44ce-adaf-529531549e48",
    "varname": "asdfg",
    "dpName": "test",
    "colName": "Sign in body",
    "parentType": "module",
    "subParentId": "SCR1052",
    "encrypt": false,
    "type": "DATAPROVIDER",
    "isSystemVariable": false,
    "users": [],
    "excludeUsers": [],
    "deleteUsers": [],
    "activeStatus": false,
    "updatedStatus": false,
    "imported": false,
    "masked": false,
    "name": "test:Sign in body"
  },
  {
    createdBy: 'USR1428',
    modifiedBy: 'USR1428',
    createdByUname: 'Mohammed Saqeb',
    modifiedByUname: 'Mohammed Saqeb',
    createdOn: '07 Apr 2022 04:18 PM',
    modifiedOn: '07 Nov 2022 04:49 PM',
    state: 'NEW',
    ver: 1,
    id: 'VAR1254',
    name: 'device',
    value: 'a12snnxx',
    encrypt: false,
    type: '_startforloop',
    projectId: 'PJT1022',
    isSystemVariable: true,
    users: [],
    excludeUsers: [],
    deleteUsers: [],
    activeStatus: false,
    updatedStatus: false,
    imported: false,
    masked: false,
  },
  {
    "refId": "DP_VAR67beb6c4-3f90-4ae2-b924-119847e37f7f",
    "parentId": "MODa356ece4-1076-44ce-adaf-529531549e48",
    "varname": "t123",
    "dpName": "test",
    "colName": "Sign in url",
    "parentType": "module",
    "subParentId": "SCR1052",
    "encrypt": false,
    "type": "DATAPROVIDER",
    "isSystemVariable": false,
    "users": [],
    "excludeUsers": [],
    "deleteUsers": [],
    "activeStatus": false,
    "updatedStatus": false,
    "imported": false,
    "masked": false,
    "name": "test:Sign in url"
  },
  {
    name: "initialValue",
    value: "1",
    type: "_startforloop"
  }
];
