import { ffid } from '../../utils/ffID/ffid';
import Icon from '../Icon';

export const sampleData = [
  {
    title: 'Depends on Script',
    data: [
      {
        stepId: ffid(),
        name: 'Open Browser',
        modifiedBy: 'Ram',
        suiteName: 'test',
        isDisabled: true,
        marginLeft: 0,
      },
    ],
  },
  {
    title: 'Pre conditions',
    data: [
      {
        stepId: ffid(),
        name: 'Open Browser',
        modifiedBy: 'Ram',
        suiteName: 'test',
        isDisabled: true,
        type: 'PRE',
      },
      {
        stepId: ffid(),
        name: 'Close Browser',
        modifiedBy: 'Ram',
        suiteName: 'test',
      },
    ],
    metaData: {
      total: 1,
      totalPassed: 0,
      totalFailed: 1,
      totalWarning: 0,
      totalSkipped: 0,
      totalTerminated: 0,
      totalAborted: 0,
      totalNA: 0,
      totalPartiallyExecuted: 0,
      totalNonCascadedPreConditionFailed: 0,
      totalNonCascadedPostConditionFailed: 0,
      totalNonCascadedPreConditionWarning: 0,
      totalNonCascadedPostConditionWarning: 0,
      executionDuration: 30057,
      executionDurationInHourMinSecFormat: '00:00:30:57',
      cascaded: false,
      result: 'Pre conditions are failed',
      status: 'FAIL',
    },
  },
  {
    title: 'Steps',
    data: [
      {
        name: 'Start for loop',
        type: '_startforloop',
        nlpName: 'StartForLoop',
        executionOrder: 1,
        nlpId: 'NLP1810',
        passMessage: 'Start for loop is passed',
        failMessage: 'Start for loop is failed',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Start for loop',
        displayName: 'Start for loop',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Start for loop',
        stepId: 'STP41499M2D13H10M37S33M980R57',
        toolTip: 'Start for loop',
        defaultToolTip: 'Start for loop',
        hierarchy: 0,
        specialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        isSpecialNlp: true,
        marginLeft: 0,
        dataProviderVariables: [],
        mustExecute: false,
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
        stepResultStats: {
          total: 2,
          totalPassed: 0,
          totalFailed: 2,
          totalWarning: 0,
          totalSkipped: 0,
          totalTerminated: 0,
          totalAborted: 0,
          totalNA: 0,
          totalPartiallyExecuted: 0,
          totalNonCascadedPreConditionFailed: 0,
          totalNonCascadedPostConditionFailed: 0,
          totalNonCascadedPreConditionWarning: 0,
          totalNonCascadedPostConditionWarning: 0,
          executionDuration: 20022,
          executionDurationInHourMinSecFormat: '00:00:20:22',
          result: 'Steps are Failed',
          status: 'Failed',
        },
      },
      {
        name: 'Start If Condition',
        type: 'step',
        nlpName: 'IfCondition',
        executionOrder: 2,
        nlpId: 'NLP1401',
        passMessage: 'Condition is true',
        failMessage: 'Condition is false',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Start If Condition',
        displayName: 'Start If Condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Start If Condition',
        stepId: 'STP16184M2D13H10M38S42M423R60',
        toolTip: 'Start If Condition',
        defaultToolTip: 'Start If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        dataProviderVariables: [],
        conditionId: 'CON699213103842424',
        conditionSearchKey: 'CON699213103842424',
        mustExecute: false,
        isForLoopStep: true,
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'OpenBrowser',
        type: 'Group',
        nlpName: 'OpenBrowser',
        executionOrder: 3,
        nlpId: 'SG_NLP1425',
        passMessage: 'OpenBrowser is passed',
        failMessage: 'OpenBrowser is failed',
        skip: false,
        returnType: 'void',
        libraryId: 'LIBbf1e19d8-a58b-49df-870d-194e66e29cc0',
        stepGroupId: 'STP_GRP227e025e-952b-45f7-b30e-9ba52a39f04d',
        platform: 'Web',
        displayName: 'OpenBrowser',
        defaultDisplayName: 'OpenBrowser',
        stepId: 'STP72955M2D13H10M45S5M922R32',
        toolTip: 'Open and Close Browser : OpenBrowser : Web',
        defaultToolTip: 'OpenBrowser',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON699213103842424',
        conditionSearchKey: 'CON699213103842424',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '1',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Start for loop',
        type: '_startforloop',
        nlpName: 'StartForLoop',
        executionOrder: 4,
        nlpId: 'NLP1810',
        passMessage: 'Start for loop is passed',
        failMessage: 'Start for loop is failed',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Start for loop',
        displayName: 'Start for loop',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Start for loop',
        stepId: 'STP31614M2D13H10M48S34M815R26',
        toolTip: 'Start for loop',
        defaultToolTip: 'Start for loop',
        hierarchy: 0,
        specialNlpId: 'forloop_548248f0-c7d9-4ff6-bee0-9b92e74e3c7e',
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON699213103842424',
        conditionSearchKey: 'CON699213103842424',
        mustExecute: false,
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Navigate to URL https://www.myntra.com/',
        type: 'step',
        nlpName: 'NavigateToURL',
        executionOrder: 5,
        nlpId: 'NLP1099',
        passMessage: 'Navigated to URL *url*',
        failMessage: 'Failed to navigate to URL *url*',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Navigate to *url*',
        displayName: 'Navigate to URL https://www.myntra.com/',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Navigate to URL *url*',
        stepId: 'STP71414M2D13H10M49S24M219R46',
        toolTip: 'Navigate to URL https://www.myntra.com/',
        defaultToolTip: 'Navigate to URL *url*',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_548248f0-c7d9-4ff6-bee0-9b92e74e3c7e',
        marginLeft: 24,
        dataProviderVariables: [],
        conditionId: 'CON699213103842424',
        conditionSearchKey: 'CON699213103842424',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '2',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'End for loop',
        type: '_endforloop',
        nlpName: 'EndForLoop',
        executionOrder: 6,
        nlpId: 'NLP1702',
        passMessage: 'End for loop passed',
        failMessage: 'End for loop failed',
        stepInputs: [],
        skip: false,
        returnType: 'Void',
        nlpType: 'NLP',
        platform: 'Web',
        searchName: 'End for loop',
        displayName: 'End for loop',
        description: 'This NLP is used to end for loop',
        defaultDisplayName: 'End for loop',
        stepId: 'STP47099M2D13H10M48S34M815R66',
        toolTip: 'End for loop',
        hierarchy: 0,
        specialNlpId: 'forloop_548248f0-c7d9-4ff6-bee0-9b92e74e3c7e',
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        conditionId: 'CON699213103842424',
        conditionSearchKey: 'CON699213103842424',
        mustExecute: false,
        imported: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'End If Condition',
        type: 'step',
        nlpName: 'EndIfCondition',
        executionOrder: 7,
        nlpId: 'NLP1405',
        passMessage: 'End If Condition passed',
        failMessage: 'End If Condition failed',
        stepInputs: [],
        skip: false,
        returnType: 'void',
        nlpType: 'NLP',
        platform: 'Common',
        packageName: 'com.tyss.optimize.nlp.Nlp',
        searchName: 'End If Condition',
        displayName: 'End If Condition',
        description: 'This NLP is used to end if condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'End If Condition',
        stepId: 'STP443M2D13H10M38S42M424R64',
        toolTip: 'End If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        conditionId: 'CON699213103842424',
        conditionSearchKey: 'CON699213103842424',
        mustExecute: false,
        imported: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Start Else If Condition',
        type: 'step',
        nlpName: 'ElseIfCondition',
        executionOrder: 8,
        nlpId: 'NLP1395',
        passMessage: 'Condition is true',
        failMessage: 'Condition is false',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Start Else If Condition',
        displayName: 'Start Else If Condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Start Else If Condition',
        stepId: 'STP21359M2D13H10M49S52M672R66',
        toolTip: 'Start Else If Condition',
        defaultToolTip: 'Start Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        dataProviderVariables: [],
        conditionId: 'CON772213104952673',
        conditionSearchKey: 'CON699213103842424/CON772213104952673',
        mustExecute: false,
        isForLoopStep: true,
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Wait for 3 seconds',
        type: 'step',
        nlpName: 'Sleep',
        executionOrder: 9,
        nlpId: 'NLP1008',
        passMessage: 'Completed wait for *seconds* seconds',
        failMessage: 'Failed to wait for *seconds* seconds',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Wait for *seconds* seconds',
        displayName: 'Wait for 3 seconds',
        actualFailedResult: 'Failed to wait for *seconds* seconds',
        defaultDisplayName: 'Wait for *seconds* seconds',
        stepId: 'STP54943M2D13H10M49S59M988R27',
        toolTip: 'Wait for 3 seconds',
        defaultToolTip: 'Wait for *seconds* seconds',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON772213104952673',
        conditionSearchKey: 'CON699213103842424/CON772213104952673',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '3',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Press Shift key',
        type: 'step',
        nlpName: 'PressShiftKey',
        executionOrder: 10,
        nlpId: 'NLP1032',
        passMessage: 'Shift key is pressed',
        failMessage: 'Failed to press Shift key',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Keyboard : Press Shift key',
        displayName: 'Press Shift key',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Press Shift key',
        stepId: 'STP13892M2D13H10M50S8M594R29',
        toolTip: 'Press Shift key',
        defaultToolTip: 'Press Shift key',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON772213104952673',
        conditionSearchKey: 'CON699213103842424/CON772213104952673',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '4',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Press ArrowLeft key',
        type: 'step',
        nlpName: 'PressArrowLeft',
        executionOrder: 11,
        nlpId: 'NLP1024',
        passMessage: 'ArrowLeft key is pressed',
        failMessage: 'Failed to press ArrowLeft key',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Keyboard : Press ArrowLeft key',
        displayName: 'Press ArrowLeft key',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Press ArrowLeft key',
        stepId: 'STP77044M2D13H10M50S15M522R30',
        toolTip: 'Press ArrowLeft key',
        defaultToolTip: 'Press ArrowLeft key',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON772213104952673',
        conditionSearchKey: 'CON699213103842424/CON772213104952673',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '5',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'End Else If Condition',
        type: 'step',
        nlpName: 'EndElseIfCondition',
        executionOrder: 12,
        nlpId: 'NLP1399',
        passMessage: 'End Else If Condition passed',
        failMessage: 'End Else If Condition failed',
        stepInputs: [],
        skip: false,
        returnType: 'void',
        nlpType: 'NLP',
        platform: 'Common',
        packageName: 'com.tyss.optimize.nlp.Nlp',
        searchName: 'End Else If Condition',
        displayName: 'End Else If Condition',
        description: 'This NLP is used to end else if condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'End Else If Condition',
        stepId: 'STP19326M2D13H10M49S52M673R38',
        toolTip: 'End Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        conditionId: 'CON772213104952673',
        conditionSearchKey: 'CON699213103842424/CON772213104952673',
        mustExecute: false,
        imported: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Start Else If Condition',
        type: 'step',
        nlpName: 'ElseIfCondition',
        executionOrder: 13,
        nlpId: 'NLP1395',
        passMessage: 'Condition is true',
        failMessage: 'Condition is false',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Start Else If Condition',
        displayName: 'Start Else If Condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Start Else If Condition',
        stepId: 'STP2568M2D13H10M50S50M669R57',
        toolTip: 'Start Else If Condition',
        defaultToolTip: 'Start Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        dataProviderVariables: [],
        conditionId: 'CON204213105050670',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670',
        mustExecute: false,
        isForLoopStep: true,
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Wait for 3 seconds',
        type: 'step',
        nlpName: 'Sleep',
        executionOrder: 14,
        nlpId: 'NLP1008',
        passMessage: 'Completed wait for *seconds* seconds',
        failMessage: 'Failed to wait for *seconds* seconds',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Wait for *seconds* seconds',
        displayName: 'Wait for 3 seconds',
        actualFailedResult: 'Failed to wait for *seconds* seconds',
        defaultDisplayName: 'Wait for *seconds* seconds',
        stepId: 'STP3736M2D13H10M50S58M320R52',
        toolTip: 'Wait for 3 seconds',
        defaultToolTip: 'Wait for *seconds* seconds',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON204213105050670',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '6',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'String : Concatenate sadfvg with wedrfgh',
        type: 'step',
        nlpName: 'ConcatString',
        executionOrder: 15,
        nlpId: 'NLP1065',
        passMessage: 'Concatenated *string1* with *string2*',
        failMessage: 'Failed to concatenate *string1* with *string2*',
        skip: false,
        returnType: 'String: returnValue',
        platform: 'Common',
        searchName: 'String : Concatenate *string1* with *string2*',
        displayName: 'String : Concatenate sadfvg with wedrfgh',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'String : Concatenate *string1* with *string2*',
        stepId: 'STP80536M2D13H10M51S20M811R36',
        toolTip: 'String : Concatenate sadfvg with wedrfgh',
        defaultToolTip: 'String : Concatenate *string1* with *string2*',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON204213105050670',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '7',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'End Else If Condition',
        type: 'step',
        nlpName: 'EndElseIfCondition',
        executionOrder: 16,
        nlpId: 'NLP1399',
        passMessage: 'End Else If Condition passed',
        failMessage: 'End Else If Condition failed',
        stepInputs: [],
        skip: false,
        returnType: 'void',
        nlpType: 'NLP',
        platform: 'Common',
        packageName: 'com.tyss.optimize.nlp.Nlp',
        searchName: 'End Else If Condition',
        displayName: 'End Else If Condition',
        description: 'This NLP is used to end else if condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'End Else If Condition',
        stepId: 'STP54482M2D13H10M50S50M670R96',
        toolTip: 'End Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        conditionId: 'CON204213105050670',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670',
        mustExecute: false,
        imported: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Start Else If Condition',
        type: 'step',
        nlpName: 'ElseIfCondition',
        executionOrder: 17,
        nlpId: 'NLP1395',
        passMessage: 'Condition is true',
        failMessage: 'Condition is false',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Start Else If Condition',
        displayName: 'Start Else If Condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Start Else If Condition',
        stepId: 'STP60330M2D13H10M51S41M88R90',
        toolTip: 'Start Else If Condition',
        defaultToolTip: 'Start Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        dataProviderVariables: [],
        conditionId: 'CON68121310514188',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188',
        mustExecute: false,
        isForLoopStep: true,
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Press Shift key',
        type: 'step',
        nlpName: 'PressShiftKey',
        executionOrder: 18,
        nlpId: 'NLP1032',
        passMessage: 'Shift key is pressed',
        failMessage: 'Failed to press Shift key',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Keyboard : Press Shift key',
        displayName: 'Press Shift key',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Press Shift key',
        stepId: 'STP98471M2D13H10M52S8M506R12',
        toolTip: 'Press Shift key',
        defaultToolTip: 'Press Shift key',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON68121310514188',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '8',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Wait for 3 seconds',
        type: 'step',
        nlpName: 'Sleep',
        executionOrder: 19,
        nlpId: 'NLP1008',
        passMessage: 'Completed wait for *seconds* seconds',
        failMessage: 'Failed to wait for *seconds* seconds',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Wait for *seconds* seconds',
        displayName: 'Wait for 3 seconds',
        actualFailedResult: 'Failed to wait for *seconds* seconds',
        defaultDisplayName: 'Wait for *seconds* seconds',
        stepId: 'STP658M2D13H10M52S29M761R84',
        toolTip: 'Wait for 3 seconds',
        defaultToolTip: 'Wait for *seconds* seconds',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON68121310514188',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '9',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Print Value of 3',
        type: 'step',
        nlpName: 'PrintValue',
        executionOrder: 20,
        nlpId: 'NLP1258',
        passMessage: 'Value of *input* is *returnValue*',
        failMessage: 'Failed to print value of *input*',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Print Value',
        displayName: 'Print Value of 3',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Print Value of *input*',
        stepId: 'STP12838M2D13H10M52S42M184R57',
        toolTip: 'Print Value of 3',
        defaultToolTip: 'Print Value of *input*',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON68121310514188',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '10',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'End Else If Condition',
        type: 'step',
        nlpName: 'EndElseIfCondition',
        executionOrder: 21,
        nlpId: 'NLP1399',
        passMessage: 'End Else If Condition passed',
        failMessage: 'End Else If Condition failed',
        stepInputs: [],
        skip: false,
        returnType: 'void',
        nlpType: 'NLP',
        platform: 'Common',
        packageName: 'com.tyss.optimize.nlp.Nlp',
        searchName: 'End Else If Condition',
        displayName: 'End Else If Condition',
        description: 'This NLP is used to end else if condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'End Else If Condition',
        stepId: 'STP79063M2D13H10M51S41M88R54',
        toolTip: 'End Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        conditionId: 'CON68121310514188',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188',
        mustExecute: false,
        imported: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Start Else If Condition',
        type: 'step',
        nlpName: 'ElseIfCondition',
        executionOrder: 22,
        nlpId: 'NLP1395',
        passMessage: 'Condition is true',
        failMessage: 'Condition is false',
        skip: false,
        returnType: 'void',
        platform: 'Common',
        searchName: 'Start Else If Condition',
        displayName: 'Start Else If Condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Start Else If Condition',
        stepId: 'STP86004M2D13H10M53S16M113R73',
        toolTip: 'Start Else If Condition',
        defaultToolTip: 'Start Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        dataProviderVariables: [],
        conditionId: 'CON720213105316113',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188/CON720213105316113',
        mustExecute: false,
        isForLoopStep: true,
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Navigate to URL https://www.myntra.com/',
        type: 'step',
        nlpName: 'NavigateToURL',
        executionOrder: 23,
        nlpId: 'NLP1099',
        passMessage: 'Navigated to URL *url*',
        failMessage: 'Failed to navigate to URL *url*',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Navigate to *url*',
        displayName: 'Navigate to URL https://www.myntra.com/',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Navigate to URL *url*',
        stepId: 'STP73942M2D13H10M54S4M105R17',
        toolTip: 'Navigate to URL https://www.myntra.com/',
        defaultToolTip: 'Navigate to URL *url*',
        hierarchy: 0,
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON720213105316113',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188/CON720213105316113',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '11',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Press ArrowLeft key',
        type: 'step',
        nlpName: 'PressArrowLeft',
        executionOrder: 24,
        nlpId: 'NLP1024',
        passMessage: 'ArrowLeft key is pressed',
        failMessage: 'Failed to press ArrowLeft key',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Keyboard : Press ArrowLeft key',
        displayName: 'Press ArrowLeft key',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Press ArrowLeft key',
        stepId: 'STP14942M2D13H10M54S10M962R91',
        toolTip: 'Press ArrowLeft key',
        defaultToolTip: 'Press ArrowLeft key',
        hierarchy: 0,
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON720213105316113',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188/CON720213105316113',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '12',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Press Shift key',
        type: 'step',
        nlpName: 'PressShiftKey',
        executionOrder: 25,
        nlpId: 'NLP1032',
        passMessage: 'Shift key is pressed',
        failMessage: 'Failed to press Shift key',
        skip: false,
        returnType: 'void',
        platform: 'Web',
        searchName: 'Keyboard : Press Shift key',
        displayName: 'Press Shift key',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Press Shift key',
        stepId: 'STP86748M2D13H10M54S16M800R6',
        toolTip: 'Press Shift key',
        defaultToolTip: 'Press Shift key',
        hierarchy: 0,
        marginLeft: 16,
        dataProviderVariables: [],
        conditionId: 'CON720213105316113',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188/CON720213105316113',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '13',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'End Else If Condition',
        type: 'step',
        nlpName: 'EndElseIfCondition',
        executionOrder: 26,
        nlpId: 'NLP1399',
        passMessage: 'End Else If Condition passed',
        failMessage: 'End Else If Condition failed',
        stepInputs: [],
        skip: false,
        returnType: 'void',
        nlpType: 'NLP',
        platform: 'Common',
        packageName: 'com.tyss.optimize.nlp.Nlp',
        searchName: 'End Else If Condition',
        displayName: 'End Else If Condition',
        description: 'This NLP is used to end else if condition',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'End Else If Condition',
        stepId: 'STP64752M2D13H10M53S16M113R86',
        toolTip: 'End Else If Condition',
        hierarchy: 0,
        isSpecialNlp: true,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        conditionId: 'CON720213105316113',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188/CON720213105316113',
        mustExecute: false,
        imported: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'Get all broken links',
        type: 'step',
        nlpName: 'GetAllBrokenLinks',
        executionOrder: 27,
        nlpId: 'NLP1048',
        passMessage: 'Broken links are *returnValue*',
        failMessage: 'Failed to fetch all broken links',
        skip: false,
        returnType: 'List<String>',
        platform: 'Web',
        searchName: 'Get all broken links',
        displayName: 'Get all broken links',
        actualFailedResult: 'N/A',
        defaultDisplayName: 'Get all broken links',
        stepId: 'STP38577M2D13H10M55S1M284R46',
        toolTip: 'Get all broken links',
        defaultToolTip: 'Get all broken links',
        hierarchy: 0,
        parentSpecialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        marginLeft: 8,
        dataProviderVariables: [],
        conditionId: 'CON68121310514188',
        conditionSearchKey:
          'CON699213103842424/CON772213104952673/CON204213105050670/CON68121310514188',
        mustExecute: false,
        isForLoopStep: true,
        displayOrder: '14',
        imported: false,
        isDisabled: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
      {
        name: 'End for loop',
        type: '_endforloop',
        nlpName: 'EndForLoop',
        executionOrder: 28,
        nlpId: 'NLP1702',
        passMessage: 'End for loop passed',
        failMessage: 'End for loop failed',
        stepInputs: [],
        skip: false,
        returnType: 'Void',
        nlpType: 'NLP',
        platform: 'Web',
        searchName: 'End for loop',
        displayName: 'End for loop',
        description: 'This NLP is used to end for loop',
        defaultDisplayName: 'End for loop',
        stepId: 'STP82202M2D13H10M37S33M981R22',
        toolTip: 'End for loop',
        hierarchy: 0,
        specialNlpId: 'forloop_d5a18760-eb7a-42d9-b17d-658815b94ca1',
        isSpecialNlp: true,
        marginLeft: 0,
        mustExecute: false,
        imported: false,
        isStepGroupStep: false,
        isJDBCStep: false,
        afterBreakStep: false,
        afterContinueStep: false,
      },
    ],
    metaData: {
      total: 10,
      totalPassed: 6,
      totalFailed: 1,
      totalWarning: 0,
      totalSkipped: 0,
      totalTerminated: 0,
      totalAborted: 0,
      totalNA: 3,
      totalPartiallyExecuted: 0,
      totalNonCascadedPreConditionFailed: 0,
      totalNonCascadedPostConditionFailed: 0,
      totalNonCascadedPreConditionWarning: 0,
      totalNonCascadedPostConditionWarning: 0,
      executionDuration: 80129,
      executionDurationInHourMinSecFormat: '00:01:20:129',
      result: 'One or more steps are failed',
      status: 'FAIL',
    },
    actionCell: () => {
      return (
        <div style={{ display: 'flex', justifyContent: 'space-around' }}>
          <Icon name="no_access_icon" />
          <Icon name="step_group" />
          <Icon name="delete" />
        </div>
      );
    },
  },
  {
    title: 'Post conditions',
    data: [
      {
        stepId: ffid(),
        name: 'close browser',
        modifiedBy: 'Krishna',
        suiteName: 'test 2',
        type: 'POST',
      },
    ],
  },
];
