const extendedData = [
  {
    subModuleCount: 15,
    title: 'FIreFlink',
    scriptCount: 0,
    path: '/Root',
    expanded: true,
    modifiedOn: '19-12-2023 15:32',
    children: [
      {
        subModuleCount: 10,
        title: 'Home',
        scriptCount: 0,
        path: '/Root/Home',
        expanded: true,
        modifiedOn: '19-12-2023 15:43',
        folder: true,
        children: [
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 4,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1003',
            modifiedByUname: '--',
            title: 'Setup',
            scriptCount: 0,
            executionOrder: 1,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Setup',
            expanded: false,
            modifiedOn: '19-12-2023 16:40',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Setup',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1003',
            folder: true,
            children: [
              {
                ver: 1,
                hierarchy: 3,
                subModuleCount: 0,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1002/MOD1003/MOD1101',
                modifiedByUname: '--',
                title: 'Initial Setup',
                scriptCount: 0,
                executionOrder: 1,
                createdByUname: 'Shivaprasad',
                parentId: 'MOD1003',
                path: '/Root/Home/Setup/Initial Setup',
                expanded: false,
                modifiedOn: '20-12-2023 09:00',
                parentName: 'Setup',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Initial Setup',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1101',
              },
              {
                ver: 1,
                hierarchy: 3,
                subModuleCount: 0,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1002/MOD1003/MOD1102',
                modifiedByUname: '--',
                title: 'Advanced Setup',
                scriptCount: 0,
                executionOrder: 2,
                createdByUname: 'Shivaprasad',
                parentId: 'MOD1003',
                path: '/Root/Home/Setup/Advanced Setup',
                expanded: false,
                modifiedOn: '20-12-2023 09:30',
                parentName: 'Setup',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Advanced Setup',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1102',
              },
              {
                ver: 1,
                hierarchy: 3,
                subModuleCount: 0,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1002/MOD1003/MOD1103',
                modifiedByUname: '--',
                title: 'Setup Review',
                scriptCount: 0,
                executionOrder: 3,
                createdByUname: 'Shivaprasad',
                parentId: 'MOD1003',
                path: '/Root/Home/Setup/Setup Review',
                expanded: false,
                modifiedOn: '20-12-2023 10:00',
                parentName: 'Setup',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Setup Review',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1103',
              },
            ],
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 4,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1002/MOD1004',
            modifiedByUname: '--',
            title: 'Authoring',
            scriptCount: 0,
            executionOrder: 2,
            createdByUname: 'Shivaprasad',
            parentId: 'MOD1002',
            path: '/Root/Home/Authoring Cycle',
            expanded: false,
            modifiedOn: '19-12-2023 16:40',
            parentName: 'Home',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Authoring Cycle',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1004',
            folder: true,
            children: [
              {
                ver: 1,
                hierarchy: 3,
                subModuleCount: 0,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1002/MOD1004/MOD1201',
                modifiedByUname: '--',
                title: 'Draft Authoring',
                scriptCount: 0,
                executionOrder: 1,
                createdByUname: 'Shivaprasad',
                parentId: 'MOD1004',
                path: '/Root/Home/Authoring Cycle/Draft Authoring',
                expanded: false,
                modifiedOn: '21-12-2023 11:00',
                parentName: 'Authoring Cycle',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Draft Authoring',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1201',
              },
              {
                ver: 1,
                hierarchy: 3,
                subModuleCount: 0,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1002/MOD1004/MOD1202',
                modifiedByUname: '--',
                title: 'Peer Review',
                scriptCount: 0,
                executionOrder: 2,
                createdByUname: 'Shivaprasad',
                parentId: 'MOD1004',
                path: '/Root/Home/Authoring Cycle/Peer Review',
                expanded: false,
                modifiedOn: '21-12-2023 11:30',
                parentName: 'Authoring Cycle',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Peer Review',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1202',
              },
            ],
          },
          {
            subModuleCount: 10,
            title: 'Home',
            scriptCount: 0,
            path: '/Root/Home',
            expanded: false,
            modifiedOn: '19-12-2023 15:43',
            folder: true,
            children: [
              {
                ver: 1,
                hierarchy: 2,
                subModuleCount: 4,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1002/MOD1003',
                modifiedByUname: '--',
                title: 'Setup',
                scriptCount: 0,
                executionOrder: 1,
                createdByUname: 'Shivaprasad',
                parentId: 'MOD1002',
                path: '/Root/Home/Setup',
                expanded: false,
                modifiedOn: '19-12-2023 16:40',
                parentName: 'Home',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Setup',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1003',
                folder: true,
                children: [
                  {
                    ver: 1,
                    hierarchy: 3,
                    subModuleCount: 0,
                    assigneeCount: 0,
                    searchKey: '/MOD1001/MOD1002/MOD1003/MOD1101',
                    modifiedByUname: '--',
                    title: 'Initial Setup',
                    scriptCount: 0,
                    executionOrder: 1,
                    createdByUname: 'Shivaprasad',
                    parentId: 'MOD1003',
                    path: '/Root/Home/Setup/Initial Setup',
                    expanded: false,
                    modifiedOn: '20-12-2023 09:00',
                    parentName: 'Setup',
                    moduleLevelScriptCount: 0,
                    lastExecutionOrder: 0,
                    imported: false,
                    name: 'Initial Setup',
                    modifiedBy: '--',
                    moduleCountWithScript: 0,
                    state: 'NEW',
                    key: 'MOD1101',
                  },
                  {
                    ver: 1,
                    hierarchy: 3,
                    subModuleCount: 0,
                    assigneeCount: 0,
                    searchKey: '/MOD1001/MOD1002/MOD1003/MOD1102',
                    modifiedByUname: '--',
                    title: 'Advanced Setup',
                    scriptCount: 0,
                    executionOrder: 2,
                    createdByUname: 'Shivaprasad',
                    parentId: 'MOD1003',
                    path: '/Root/Home/Setup/Advanced Setup',
                    expanded: false,
                    modifiedOn: '20-12-2023 09:30',
                    parentName: 'Setup',
                    moduleLevelScriptCount: 0,
                    lastExecutionOrder: 0,
                    imported: false,
                    name: 'Advanced Setup',
                    modifiedBy: '--',
                    moduleCountWithScript: 0,
                    state: 'NEW',
                    key: 'MOD1102',
                  },
                  {
                    ver: 1,
                    hierarchy: 3,
                    subModuleCount: 0,
                    assigneeCount: 0,
                    searchKey: '/MOD1001/MOD1002/MOD1003/MOD1103',
                    modifiedByUname: '--',
                    title: 'Setup Review',
                    scriptCount: 0,
                    executionOrder: 3,
                    createdByUname: 'Shivaprasad',
                    parentId: 'MOD1003',
                    path: '/Root/Home/Setup/Setup Review',
                    expanded: false,
                    modifiedOn: '20-12-2023 10:00',
                    parentName: 'Setup',
                    moduleLevelScriptCount: 0,
                    lastExecutionOrder: 0,
                    imported: false,
                    name: 'Setup Review',
                    modifiedBy: '--',
                    moduleCountWithScript: 0,
                    state: 'NEW',
                    key: 'MOD1103',
                  },
                ],
              },
              {
                ver: 1,
                hierarchy: 2,
                subModuleCount: 4,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1002/MOD1004',
                modifiedByUname: '--',
                title: 'Authoring Cycle',
                scriptCount: 0,
                executionOrder: 2,
                createdByUname: 'Shivaprasad',
                parentId: 'MOD1002',
                path: '/Root/Home/Authoring Cycle',
                expanded: false,
                modifiedOn: '19-12-2023 16:40',
                parentName: 'Home',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Authoring Cycle',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1004',
                folder: true,
                children: [
                  {
                    ver: 1,
                    hierarchy: 3,
                    subModuleCount: 0,
                    assigneeCount: 0,
                    searchKey: '/MOD1001/MOD1002/MOD1004/MOD1201',
                    modifiedByUname: '--',
                    title: 'Draft Authoring',
                    scriptCount: 0,
                    executionOrder: 1,
                    createdByUname: 'Shivaprasad',
                    parentId: 'MOD1004',
                    path: '/Root/Home/Authoring Cycle/Draft Authoring',
                    expanded: false,
                    modifiedOn: '21-12-2023 11:00',
                    parentName: 'Authoring Cycle',
                    moduleLevelScriptCount: 0,
                    lastExecutionOrder: 0,
                    imported: false,
                    name: 'Draft Authoring',
                    modifiedBy: '--',
                    moduleCountWithScript: 0,
                    state: 'NEW',
                    key: 'MOD1201',
                  },
                  {
                    ver: 1,
                    hierarchy: 3,
                    subModuleCount: 0,
                    assigneeCount: 0,
                    searchKey: '/MOD1001/MOD1002/MOD1004/MOD1202',
                    modifiedByUname: '--',
                    title: 'Peer Review',
                    scriptCount: 0,
                    executionOrder: 2,
                    createdByUname: 'Shivaprasad',
                    parentId: 'MOD1004',
                    path: '/Root/Home/Authoring Cycle/Peer Review',
                    expanded: false,
                    modifiedOn: '21-12-2023 11:30',
                    parentName: 'Authoring Cycle',
                    moduleLevelScriptCount: 0,
                    lastExecutionOrder: 0,
                    imported: false,
                    name: 'Peer Review',
                    modifiedBy: '--',
                    moduleCountWithScript: 0,
                    state: 'NEW',
                    key: 'MOD1202',
                  },
                ],
              },
            ],
          },
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1021/MOD1022',
            modifiedByUname: '--',
            title: 'Login',
            scriptCount: 0,
            executionOrder: 1,
            createdByUname: 'Natacha',
            parentId: 'MOD1021',
            path: '/Root/Test/Login',
            expanded: false,
            modifiedOn: '10-01-2024 20:57',
            parentName: 'Test',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Login',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1022',
          },
          {
            subModuleCount: 5,
            title: 'Test',
            scriptCount: 0,
            path: '/Root/Test',
            expanded: false,
            modifiedOn: '10-01-2024 20:56',
            folder: true,
            children: [
              {
                ver: 1,
                hierarchy: 2,
                subModuleCount: 0,
                assigneeCount: 0,
                searchKey: '/MOD1001/MOD1021/MOD1022',
                modifiedByUname: '--',
                title: 'Login',
                scriptCount: 0,
                executionOrder: 1,
                createdByUname: 'Natacha',
                parentId: 'MOD1021',
                path: '/Root/Test/Login',
                expanded: false,
                modifiedOn: '10-01-2024 20:57',
                parentName: 'Test',
                moduleLevelScriptCount: 0,
                lastExecutionOrder: 0,
                imported: false,
                name: 'Login',
                modifiedBy: '--',
                moduleCountWithScript: 0,
                state: 'NEW',
                key: 'MOD1022',
              },
            ],
          },
        ],
      },
      {
        subModuleCount: 5,
        title: 'Test',
        scriptCount: 0,
        path: '/Root/Test',
        expanded: true,
        modifiedOn: '10-01-2024 20:56',
        folder: true,
        children: [
          {
            ver: 1,
            hierarchy: 2,
            subModuleCount: 0,
            assigneeCount: 0,
            searchKey: '/MOD1001/MOD1021/MOD1022',
            modifiedByUname: '--',
            title: 'Login',
            scriptCount: 0,
            executionOrder: 1,
            createdByUname: 'Natacha',
            parentId: 'MOD1021',
            path: '/Root/Test/Login',
            expanded: false,
            modifiedOn: '10-01-2024 20:57',
            parentName: 'Test',
            moduleLevelScriptCount: 0,
            lastExecutionOrder: 0,
            imported: false,
            name: 'Login',
            modifiedBy: '--',
            moduleCountWithScript: 0,
            state: 'NEW',
            key: 'MOD1022',
          },
        ],
      },
      {
        ver: 1,
        hierarchy: 1,
        subModuleCount: 0,
        assigneeCount: 0,
        searchKey: '/MOD1001/MOD1024',
        modifiedByUname: '--',
        title: 'Others',
        scriptCount: 0,
        executionOrder: 3,
        createdByUname: 'Solabs',
        parentId: 'MOD1001',
        path: '/Root/Others',
        expanded: false,
        modifiedOn: '18-01-2024 16:14',
        parentName: 'Root Module',
        folder: true,
        moduleLevelScriptCount: 0,
        lastExecutionOrder: 0,
        imported: false,
        name: 'Others',
        modifiedBy: '--',
        moduleCountWithScript: 0,
        state: 'NEW',
        key: 'MOD1024',
        children: [ {
          subModuleCount: 5,
          title: 'Test',
          scriptCount: 0,
          path: '/Root/Test',
          expanded: false,
          modifiedOn: '10-01-2024 20:56',
          folder: true,
          children: [
            {
              ver: 1,
              hierarchy: 2,
              subModuleCount: 0,
              assigneeCount: 0,
              searchKey: '/MOD1001/MOD1021/MOD1022',
              modifiedByUname: '--',
              title: 'Login',
              scriptCount: 0,
              executionOrder: 1,
              createdByUname: 'Natacha',
              parentId: 'MOD1021',
              path: '/Root/Test/Login',
              expanded: false,
              modifiedOn: '10-01-2024 20:57',
              parentName: 'Test',
              moduleLevelScriptCount: 0,
              lastExecutionOrder: 0,
              imported: false,
              name: 'Login',
              modifiedBy: '--',
              moduleCountWithScript: 0,
              state: 'NEW',
              key: 'MOD1022',
            },
          ],
        },],
      },
    ],
    lastExecutionOrder: 3,
    imported: false,
    modifiedBy: '--',
    moduleCountWithScript: 1,
    state: 'NEW',
    key: 'MOD1001',
    ver: 1,
    hierarchy: 0,
    assigneeCount: 0,
    searchKey: '/MOD1001',
    modifiedByUname: '--',
    executionOrder: 0,
    createdByUname: 'Shivaprasad',
    folder: true,
    moduleLevelScriptCount: 0,
    name: 'Root Module',
  },
];

export default extendedData;
