export type TreeNodeProps = {
  createdBy?: string;
  modifiedBy?: string;
  createdByUname?: string;
  modifiedByUname?: string;
  createdOn?: string;
  modifiedOn?: string;
  state?: string;
  path?: string;
  searchKey?: string;
  key: string;
  name?: string;
  projectId?: string;
  hierarchy: number;
  executionOrder?: number;
  subContainerCount?: number;
  resourceCount?: number;
  totalSubContainerCount?: number;
  totalResourceCount?: number;
  totalProjectElementCount?: number;
  totalSharedElementCount?: number;
  container?: boolean;
  localDelete?: boolean;
  defaultEntity?: boolean;
  lastResource?: boolean;
  platform?: string;
  parentId?: string;
  parentName?: string;
  checked?: boolean | 'partial';
  expanded?: boolean;
  expandable?: boolean;
  sourceId?: string;
  isNewNode?: boolean;
  entityType?: string;
  type?: string;
  label?: string;
  isShared?: boolean | string;
  isRecorded?: string;
  originalId?: string;
  locatorsCount?: number;
  version?: string;
  hide?: boolean;
  folder?: boolean;
  selectedStatus?: 'completely' | 'partially' | 'none';
  isDelete?: boolean;
  reviewerId?: string;
  reviewerName?: string;
  localCopyId?: string;
  localAutomationId?: string;
  localManualId?: string;
  cascaded?: string;
  automationId?: string;
  manualId?: string;
};
