export const Data = [
  {
    sheetName: 'Sheet1',
    data: [
      [
        {
          value: 'Test Steps',
          style: {
            name: 'Arial',
            size: 10,
            bold: false,
            italic: false,
            underline: true,
            color: '3D0301',
            backgroundColor: 'C6E7FF',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          contextDisable: {
            'Delete Column': true,
            'Delete Row': true,
            'Add Row Top': true,
          },
        },
        {
          value: 'Input',
          style: {
            name: 'Arial',
            size: 10,
            bold: false,
            italic: false,
            underline: true,
            color: '3D0301',
            backgroundColor: 'C6E7FF',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },

          contextDisable: {
            'Delete Column': true,
            'Delete Row': true,
            'Add Row Top': true,
          },
        },
        {
          value: 'Expected Result',
          style: {
            name: 'Arial',
            size: 10,
            bold: false,
            italic: false,
            underline: true,
            color: '3D0301',
            backgroundColor: 'C6E7FF',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
        },
        {
          style: {
            name: 'Arial',
            size: 10,
            bold: false,
            italic: false,
            underline: true,
            color: '3D0301',
            backgroundColor: 'C6E7FF',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: 'Actual Result',
        },
        {
          style: {
            name: 'Arial',
            size: 10,
            bold: false,
            italic: false,
            underline: true,
            color: '3D0301',
            backgroundColor: 'C6E7FF',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: 'Attachment',
        },
        {
          style: {
            name: 'Arial',
            size: 10,
            bold: false,
            italic: false,
            underline: true,
            color: '3D0301',
            backgroundColor: 'C6E7FF',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: 'Status',
        },
        {
          style: {
            name: 'Arial',
            size: 10,
            bold: false,
            italic: false,
            underline: true,
            color: '3D0301',
            backgroundColor: 'C6E7FF',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: 'Comment',
        },
      ],
      [
        {
          value: 'Times New Roman',
          style: {
            name: 'Times New Roman',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: 'F2F2F2',
            border: {
              top: 'MEDIUM',
              right: 'MEDIUM',
              bottom: 'MEDIUM',
              left: 'MEDIUM',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
        },
        {
          value: 'Trebuchet MS',
          style: {
            name: 'Trebuchet MS',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
        },
        {
          value: '1 Comic Sans MS',
          style: {
            name: 'Comic Sans MS',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: 'F2F2F2',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
        },
        {
          style: {
            name: 'Arial Black',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: 'Arial Black',
        },
        {
          style: {
            name: 'Poppins',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'file',
          },
          value:
            '[{"createdBy":"USR18162","modifiedBy":"USR18162","createdByUname":"Karthikeyan V","modifiedByUname":"Karthikeyan V","createdOn":"08 Mar 2025 04:42 AM","modifiedOn":"08 Mar 2025 04:42 AM","state":"APPROVED","searchKey":"/FLDR1017/FLDR1020/FILE1416","parentId":"FLDR1020","sourceId":"FLDR1020","inputAction":"add","id":"FILE1417","name":"basic (3).png*49397f5b-d5ba-4304-bbc0-40cd05bcbd86","projectId":"PJT1005","folder":false,"executionOrder":0,"imported":false},{"createdBy":"USR18162","modifiedBy":"USR18162","createdByUname":"Karthikeyan V","modifiedByUname":"Karthikeyan V","createdOn":"08 Mar 2025 04:42 AM","modifiedOn":"08 Mar 2025 04:42 AM","state":"APPROVED","searchKey":"/FLDR1017/FLDR1020/FILE1416","parentId":"FLDR1020","sourceId":"FLDR1020","inputAction":"add","id":"FILE1418","name":"basic (5).png*49397f5b-d5ba-4304-bbc0-40cd05bcbd86","projectId":"PJT1005","folder":false,"executionOrder":0,"imported":false},{"createdBy":"USR18162","modifiedBy":"USR18162","createdByUname":"Karthikeyan V","modifiedByUname":"Karthikeyan V","createdOn":"08 Mar 2025 04:42 AM","modifiedOn":"08 Mar 2025 04:42 AM","state":"APPROVED","searchKey":"/FLDR1017/FLDR1020/FILE1416","parentId":"FLDR1020","sourceId":"FLDR1020","inputAction":"add","id":"FILE1416","name":"basic (4).png*49397f5b-d5ba-4304-bbc0-40cd05bcbd86","projectId":"PJT1005","folder":false,"executionOrder":0,"imported":false}]',
        },
        {
          style: {
            name: 'Poppins',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'dropDown',
            options: [
              {
                disable: false,
                label: 'pass',
                name: 'pass',
                value: 'pass',
              },
              {
                disable: false,
                label: 'fail',
                name: 'fail',
                value: 'fail',
              },
            ],
          },
          value: 'pass',
        },
        {
          style: {
            name: 'Lucida Console',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: 'Lucida Console',
        },
      ],
      [
        {
          value: 'Lucida Sans Unicode',
          style: {
            name: 'Lucida Sans Unicode',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
        },
        {
          value: 'Arial Rounded MT Bold',
          style: {
            name: 'Arial Rounded MT Bold',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
        },
        {
          value: '',
          style: {
            name: 'Poppins',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: 'c9c9c9',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
        },
        {
          style: {
            name: 'Poppins',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: '',
        },
        {
          style: {
            name: 'Poppins',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'file',
          },
          value: '',
        },
        {
          style: {
            name: 'Poppins',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'dropDown',
            options: [
              {
                disable: false,
                title: 'warning',
                label: 'warning',
                value: 'warning',
                color: 'orange',
              },
              {
                disable: false,
                title: 'fail',
                label: 'fail',
                value: 'fail',
                color: 'red',
              },
              {
                disable: false,
                title: 'skipped',
                label: 'skipped',
                value: 'skipped',
                color: 'grey',
              },
              {
                disable: false,
                title: 'pass',
                label: 'green',
                value: 'pass',
                color: 'green',
              },
            ],
          },
          value: '',
        },
        {
          style: {
            name: 'Poppins',
            size: 9,
            bold: false,
            italic: false,
            underline: false,
            color: '000000',
            backgroundColor: 'ffffff',
            borderColor: '000000',
            border: {
              top: 'THIN',
              right: 'THIN',
              bottom: 'THIN',
              left: 'THIN',
            },
            alignment: {
              horizontal: 'LEFT',
              vertical: 'BOTTOM',
              wrapText: false,
            },
          },
          readOnly: false,
          inputType: {
            type: 'text',
          },
          value: '',
        },
      ],
    ],
  },
];
