let Components: any = {};

import ManageApps from '../../assets/icons/manage_apps.svg?react';
import Logo from '../../assets/icons/logo.svg?react';
import ArrowUp from '../../assets/icons/arrow_up.svg?react';
import ArrowRight from '../../assets/icons/arrow_right.svg?react';
import AccordionHeaderIcon from '../../assets/icons/accordion_header_icon.svg?react';
import DeleteInfoIcon from '../../assets/icons/delete_info.svg?react';
import WarningIcon from '../../assets/icons/warning.svg?react';
import ToastInfoIcon from '../../assets/icons/info.svg?react';
import ToastErrorIcon from '../../assets/icons/error.svg?react';
import ToastCloseIcon from '../../assets/icons/close_icon.svg?react';
import ToastSuccessIcon from '../../assets/icons/success.svg?react';
import MoreIcon from '../../assets/icons/more.svg?react';
import DropZoneIcon from '../../assets/icons/dropzone_icon.svg?react';
import File from '../../assets/icons/file.svg?react';
import Replace from '../../assets/icons/replace.svg?react';
import Remove from '../../assets/icons/remove.svg?react';
import PlusIcon from '../../assets/icons/plus_icon.svg?react';
import ArrowsTopIcon from '../../assets/icons/arrows_top_icon.svg?react';
import ArrowsRightIcon from '../../assets/icons/arrows_right_icon.svg?react';
import ArrowsDownIcon from '../../assets/icons/arrows_down_icon.svg?react'; // import ArrowUp from '../../assets/icons/arrow_up.svg?react';
import ArrowDown from '../../assets/icons/arrow_down.svg?react';
import ClosePill from '../../assets/icons/close_pill.svg?react';
import MoonStarsIcon from '../../assets/icons/moon_stars.svg?react';
import SunIcon from '../../assets/icons/sun_icon.svg?react';
import CheckMarkIcon from '../../assets/icons/check_mark.svg?react';
import WrongMarkIcon from '../../assets/icons/wrong_mark.svg?react';
import FireflinkIcon from '../../assets/icons/fireflink_icon.svg?react';
import Tick from '../../assets/icons/tick_icon.svg?react';
import Search from '../../assets/icons/search.svg?react';
import Filter from '../../assets/icons/filter.svg?react';
import Alert from '../../assets/icons/alert.svg?react';
import ReplaceFile from '../../assets/icons/replace_file.svg?react';
import RightArrow from '../../assets/icons/right_arrow_icon.svg?react';
import LeftArrow from '../../assets/icons/left_arrow_icon.svg?react';
import ClockIcon from '../../assets/icons/clock_icon.svg?react';
import Edit from '../../assets/icons/edit_icon.svg?react';
import ViewIcon from '../../assets/icons/view_icon.svg?react';
import ExportCollection from '../../assets/icons/export_collection_icon.svg?react';
import RunIcon from '../../assets/icons/run_icon.svg?react';
import BeautifyIcon from '../../assets/icons/beautify_icon.svg?react';
import AddVariable from '../../assets/icons/add_variable_icon.svg?react';
import ManualLocator from '../../assets/icons/manual_locator.svg?react';
import LicenseIcon from '../../assets/icons/active_license_icon.svg?react';
import DeleteIcon from '../../assets/icons/delete.svg?react';
import DetailsIcon from '../../assets/icons/details.svg?react';
import ImpactListIcon from '../../assets/icons/impact_list.svg?react';
import Export from '../../assets/icons/export.svg?react';
import FormatePainter from '../../assets/icons/formate_painter.svg?react';
import Bold from '../../assets/icons/bold.svg?react';
import Italic from '../../assets/icons/italic.svg?react';
import StrikeThrough from '../../assets/icons/strike_through.svg?react';
import Underline from '../../assets/icons/underline.svg?react';
import DoubleUnderline from '../../assets/icons/double_underline.svg?react';
import AllBorders from '../../assets/icons/all_borders.svg?react';
import BorderBottom from '../../assets/icons/border_bottom.svg?react';
import BorderLeft from '../../assets/icons/border_left.svg?react';
import BorderRight from '../../assets/icons/border_right.svg?react';
import BorderTop from '../../assets/icons/border_top.svg?react';
import NoBorder from '../../assets/icons/no_border.svg?react';
import TextAlignCenter from '../../assets/icons/text_align_center.svg?react';
import TextAlignLeft from '../../assets/icons/text_align_left.svg?react';
import TextAlignRight from '../../assets/icons/text_align_right.svg?react';
import TextColor from '../../assets/icons/text_color.svg?react';
import FillColor from '../../assets/icons/fill_color.svg?react';
import FormulaIcon from '../../assets/icons/formula_icon.svg?react';
import ExcelCornerMenu from '../../assets/icons/excel_corner_menu.svg?react';
import AutoSaveIcon from '../../assets/icons/auto_save_icon.svg?react';
import UploadPillIcon from '../../assets/icons/upload_pill.svg?react';
import FireFlinkLoaderLogo from '../../assets/icons/fire_Flink_logo.svg?react';
import LoaderSvg from '../../assets/icons/line_loader.svg?react';

import ImportFile from '../../assets/icons/import_file.svg?react';
import ApkFileType from '../../assets/icons/apk_file_type.svg?react';
import CsvFileType from '../../assets/icons/csv_file_type.svg?react';
import CompressedFileType from '../../assets/icons/compressed_file_type.svg?react';
import HtmlFileType from '../../assets/icons/html_file_type.svg?react';
import JsonFileType from '../../assets/icons/json_file_type.svg?react';
import PdfFileType from '../../assets/icons/pdf_file_type.svg?react';
import PngFileType from '../../assets/icons/png_file_type.svg?react';
import XlsxFileType from '../../assets/icons/xlsx_file_type.svg?react';
import XmlFileType from '../../assets/icons/xml_file_type.svg?react';
import XlsFileType from '../../assets/icons/xls_file_type.svg?react';
import IpkFileType from '../../assets/icons/ipk_file_type.svg?react';
import TxtFileType from '../../assets/icons/txt_file_type.svg?react';
import GifFileType from '../../assets/icons/gif_file_type.svg?react';
import JpgFileType from '../../assets/icons/jpg_file_type.svg?react';
import DocFileType from '../../assets/icons/doc_file_type.svg?react';
import DocxFileType from '../../assets/icons/docx_file_type.svg?react';
import IpaFileType from '../../assets/icons/ipa_file_type.svg?react';
import JpegFileType from '../../assets/icons/jpeg_file_type.svg?react';
import JsFileType from '../../assets/icons/js_file_type.svg?react';
import MdFileType from '../../assets/icons/md_file_type.svg?react';
import Mp3FileType from '../../assets/icons/mp3_file_type.svg?react';
import Mp4FileType from '../../assets/icons/mp4_file_type.svg?react';
import PdfxFileType from '../../assets/icons/pdfx_file_type.svg?react';
import PemFileType from '../../assets/icons/pem_file_type.svg?react';
import PptFileType from '../../assets/icons/ppt_file_type.svg?react';
import PptxFileType from '../../assets/icons/pptx_file_type.svg?react';
import SvgFileType from '../../assets/icons/svg_file_type.svg?react';
import WFileType from '../../assets/icons/w_file_type.svg?react';
import WavFileType from '../../assets/icons/wav_file_type.svg?react';
import Y4mFileType from '../../assets/icons/y4m_file_type.svg?react';
import YmlFileType from '../../assets/icons/yml_file_type.svg?react';
import BinFileType from '../../assets/icons/bin_file_type.svg?react';
import M4vFileType from '../../assets/icons/m4v_file_type.svg?react';
import MovFileType from '../../assets/icons/mov_file_type.svg?react';
import PfxFileType from '../../assets/icons/pfx_file_type.svg?react';

import InfoIcon from '../../assets/icons/info_icon.svg?react';
import CalendarIcon from '../../assets/icons/calendar_icon.svg?react';
import HideIcon from '../../assets/icons/hide_icon.svg?react';
import VerticalSeparator from '../../assets/icons/vertical_separator.svg?react';
import CollapseIcon from '../../assets/icons/collapse-icon.svg?react';
import ExpandIcon from '../../assets/icons/expand-icon.svg?react';
import CopyIcon from '../../assets/icons/copy-icon.svg?react';
import DownloadFile from '../../assets/icons/download-icon.svg?react';
import RefreshIcon from '../../assets/icons/refresh-icon.svg?react';
import LicenseInfo from '../../assets/icons/license_info.svg?react';
import LicenseWarning from '../../assets/icons/license_warning.svg?react';
import VariableIcon from '../../assets/icons/variable_icon.svg?react';
import Windows from '../../assets/icons/windows.svg?react';
import DataListIcon from '../../assets/icons/dataset_list.svg?react';
import Mac from '../../assets/icons/mac.svg?react';
import Android from '../../assets/icons/android.svg?react';
import Chrome from '../../assets/icons/chrome.svg?react';
import BrowserStack from '../../assets/icons/browser_stack.svg?react';
import Run from '../../assets/icons/run_icon.svg?react';

import LeftNewIcon from '../../assets/icons/left_new_icon.svg?react';
import RightNewIcon from '../../assets/icons/right_new_icon.svg?react';

import DownloadIcon from '../../assets/icons/download_icon.svg?react';
import WebIcon from '../../assets/icons/web_icon.svg?react';
import WebMobileIcon from '../../assets/icons/web&mobile_icon.svg?react';
import MobileIcon from '../../assets/icons/mobile_icon.svg?react';
import SalesForceIcon from '../../assets/icons/sales_force.svg?react';
import MSDynamicIcon from '../../assets/icons/ms_dynamic.svg?react';
import AllProjectsIcon from '../../assets/icons/all_projects.svg?react';
import AndroidIcon from '../../assets/icons/android_icon.svg?react';
import NoAccessIcon from '../../assets/icons/no_access_icon.svg?react';
import FullAccessIcon from '../../assets/icons/full_access_icon.svg?react';
import ViewAccessIcon from '../../assets/icons/view_access_icon.svg?react';
import HideAccessIcon from '../../assets/icons/hide_access_icon.svg?react';
import AddLocator from '../../assets/icons/add_locator.svg?react';
import PlusUserIcon from '../../assets/icons/plus_user_icon.svg?react';

import IosIcon from '../../assets/icons/ios_icon.svg?react';
import HelpIcon from '../../assets/icons/help_icon.svg?react';
import SwitchLicenseIcon from '../../assets/icons/switch_license_icon.svg?react';
import FireflinkLogo from '../../assets/icons/fireflink_logo.svg?react';
import WSWBDeleteIcon from '../../assets/icons/wswb_delete_icon.svg?react';
import WSWBPlusIcon from '../../assets/icons/wswb_plus_icon.svg?react';
import LabelPlusIcon from '../../assets/icons/label_plus.svg?react';
import Drag from '../../assets/icons/drag_icon.svg?react';
import BackwardIcon from '../../assets/icons/backward_icon.svg?react';
import ForwardIcon from '../../assets/icons/forward_icon.svg?react';
import Reload from '../../assets/icons/reload.svg?react';
import WindowMaximize from '../../assets/icons/window_maximize.svg?react';
import WindowRestore from '../../assets/icons/window_restore.svg?react';
import WindowMinimize from '../../assets/icons/window_minimize.svg?react';
import HamburgerMenu from '../../assets/icons/hamburger_menu.svg?react';
import AppSwitchIcon from '../../assets/icons/app_switch.svg?react';
import UserProfile from '../../assets/icons/user_profile.svg?react';
import ContinueSignIn from '../../assets/icons/continue_without_sign.svg?react';
import CloudServerHost from '../../assets/icons/cloud_server_host_icon.svg?react';
import LocalVariableIcon from '../../assets/icons/local_variable_icon.svg?react';
import GlobalVariableIcon from '../../assets/icons/global_variable_icon.svg?react';
import ProjectEnvVariableIcon from '../../assets/icons/project_env_variable_icon.svg?react';
import StepGroupParameterIcon from '../../assets/icons/step_group_parameter.svg?react';
import StepGroupVariableIcon from '../../assets/icons/step_group_variable.svg?react';
import ForLoopVariableIcon from '../../assets/icons/for_loop_variable.svg?react';
import DataProviderVariableIcon from '../../assets/icons/data_provider_variable.svg?react';

import NotificationIcon from '../../assets/icons/notification_icon.svg?react';
import NLPHelpIcon from '../../assets/icons/nlp_help_icon.svg?react';
import UpdateIcon from '../../assets/icons/update_icon.svg?react';
import AddFile from '../../assets/icons/add_file.svg?react';
import AddNewFile from '../../assets/icons/add_new_file.svg?react';
import PlusRoundIcon from '../../assets/icons/plus_round_icon.svg?react';
import EyeClosed from '../../assets/icons/eye_closed.svg?react';
import AttachmentIcon from '../../assets/icons/attachment_icon.svg?react';
import AuthorizationIcon from '../../assets/icons/authorization_icon.svg?react';

import CloneIcon from '../../assets/icons/clone_icon.svg?react';
import MoveIcon from '../../assets/icons/move_icon.svg?react';
import Jira from '../../assets/icons/jira.svg?react';
import HistoryIcon from '../../assets//icons/history_icon.svg?react';
import LinkedDefects from '../../assets//icons/linked_defects.svg?react';
import FireflinkPlatform from '../../assets//icons/fireflink_platform.svg?react';
import FireflinkFinder from '../../assets//icons/fireflink_finder_logo.svg?react';
import ClientProfile from '../../assets//icons/client_profile.svg?react';
import LicenseExpired from '../../assets//icons/license_expired.svg?react';
import AddTestCaseIcon from '../../assets/icons/add_testcase.svg?react';
import AutomationTestCaseIcon from '../../assets/icons/automation_testcase.svg?react';
import ManualTestCaseIcon from '../../assets/icons/manual_testcase.svg?react';
import BackIcon from '../../assets/icons/back_icon.svg?react';
import AddFromSharedElement from '../../assets/icons/add_from_shared_elements.svg?react';
import SauseLabIcon from '../../assets/icons/sause_lab.svg?react';
import LocalIcon from '../../assets/icons/local.svg?react';
import InternetExplorerIcon from '../../assets/icons/internet_explorer.svg?react';
import BrowserstackIcon from '../../assets/icons/browserstack_icon.svg?react';
import EdgeIcon from '../../assets/icons/edge.svg?react';
import FirefoxIcon from '../../assets/icons/fire_fox.svg?react';
import LambdaIcon from '../../assets/icons/lambda_icon.svg?react';
import LinuxIcon from '../../assets/icons/linux.svg?react';
import OperaIcon from '../../assets/icons/opera.svg?react';
import SafariIcon from '../../assets/icons/safari_icon.svg?react';
import MaximizeScript from '../../assets/icons/maximize_script.svg?react';
import DownloadFileIcon from '../../assets/icons/download_file_icon.svg?react';
import MaximizeIcon from '../../assets/icons/maximize_icon.svg?react';
import PassedStatusIcon from '../../assets/icons/passed_status_icon.svg?react';
import FailedStatusIcon from '../../assets/icons/failed_status_icon.svg?react';
import WarningStatusIcon from '../../assets/icons/warning_status_icon.svg?react';
import SkippedStatusIcon from '../../assets/icons/skipped_status_icon.svg?react';
import FlakyStatusIcon from '../../assets/icons/flaky_status_icon.svg?react';
import DrawerMaximizeIcon from '../../assets/icons/drawer_maximize.svg?react';
import SaveAsStepIcon from '../../assets/icons/save_as_step.svg?react';
import SendToStepsIcon from '../../assets/icons/send_step.svg?react';
import NoLicenseFound from '../../assets/icons/no_license_found.svg?react';
import StandardTemplate from '../../assets/icons/standard_template.svg?react';
import SampleTemplateFirst from '../../assets/icons/sample_template_first.svg?react';
import SampleTemplateSecond from '../../assets/icons/sample_template_second.svg?react';
import DataProvider from '../../assets/icons/data_provider.svg?react';
import LinkExpired from '../../assets/icons/link_expired.svg?react';
import LinkReset from '../../assets/icons/reset-link.svg?react';
import SystemWarning from '../../assets/icons/system_warning.svg?react';
import UserPasswordLock from '../../assets/icons/user_password_lock.svg?react';
import UserWarning from '../../assets/icons/user_warning.svg?react';
import UserWithSystem from '../../assets/icons/user_with_system.svg?react';
import AiSearch from '../../assets/icons/ai_search.svg?react';

import Import from '../../assets/icons/import.svg?react';
import dashboardWebIcon from '../../assets/icons/dashboard_web_icon.svg?react';
import dashboardMobileIcon from '../../assets/icons/dashboard_mobile_icon.svg?react';
import dashboardWebMobileIcon from '../../assets/icons/web_mobile_icon.svg?react';
import dashboardWebServicesIcon from '../../assets/icons/web_services_icon.svg?react';
import dashboardSalesforceIcon from '../../assets/icons/salesforce_icon.svg?react';
import dashboardMsDynamicIcon from '../../assets/icons/ms_dynamic_icon.svg?react';
import MinimizeScript from '../../assets/icons/minimize_script.svg?react';
import MaximizeTree from '../../assets/icons/maximize_tree.svg?react';
import LabelIcon from '../../assets/icons/label_icon.svg?react';
import AddLabelIcon from '../../assets/icons/add_label_icon.svg?react';
import QuickRunSettingIcon from '../../assets/icons/quick_run_setting_icon.svg?react';
import RunManualTestcaseIcon from '../../assets/icons/run_manual_testcase_icon.svg?react';
import RunAutomationScriptsIcon from '../../assets/icons/run_automation_scripts_icon.svg?react';
import EyeOpenIcon from '../../assets/icons/eye_open_icon.svg?react';
import ReplaceIcon from '../../assets/icons/replace_icon.svg?react';
import HeaderPreset from '../../assets/icons/Header_preset.svg?react';
import ProjectElement from '../../assets/icons/project_element.svg?react';
import Element from '../../assets/icons/element.svg?react';
import StepGroup from '../../assets/icons/step_group.svg?react';
import Variable from '../../assets/icons/variable.svg?react';
import Defects from '../../assets/icons/defects.svg?react';
import ApprovalPending from '../../assets/icons/approval_pending.svg?react';
import Configuration from '../../assets/icons/configuration.svg?react';
import NoData from '../../assets/icons/no_data.svg?react';
import AddUser from '../../assets/icons/add_user.svg?react';
import RemoveUser from '../../assets/icons/remove_user.svg?react';
import AddToArchive from '../../assets/icons/add_archive.svg?react';
import AddVariableIcon from '../../assets/icons/add_variable.svg?react';
import DashboardIcon from '../../assets/icons/dashboard_icon.svg?react'; //TODO:this is temporary icon
import InfoUser from '../../assets/icons/info_user.svg?react';
import WebServiceIcon from '../../assets/icons/web_service_icon.svg?react';
import ProjectStatusIcon from '../../assets/icons/project_status_icon.svg?react';
import captureIcon from '../../assets/icons/capture_icon.svg?react';
import rotateIcon from '../../assets/icons/rotate_icon.svg?react';
import tapIcon from '../../assets/icons/tap_icon.svg?react';
import refreshIcon from '../../assets/icons/refresh_icon.svg?react';
import swipeIcon from '../../assets/icons/swipe_icon.svg?react';
import backward from '../../assets/icons/backward.svg?react';
import forward from '../../assets/icons/forward.svg?react';

import dependsOnScript from '../../assets/icons/depends_on_script.svg?react';
import parameters from '../../assets/icons/parameters.svg?react';
import prePostCondition from '../../assets/icons/pre_post_condition.svg?react';
import programElement from '../../assets/icons/program_element.svg?react';
import testData from '../../assets/icons/test_data.svg?react';
import testDataSet from '../../assets/icons/test_data_set.svg?react';
import emailGroup from '../../assets/icons/email_group.svg?react';
import variableSet from '../../assets/icons/variable_set.svg?react';

import machineEnableIcon from '../../assets/icons/machine_enable_icon.svg?react';
import machineDisableIcon from '../../assets/icons/machine_disable_icon.svg?react';
import suitesIcon from '../../assets/icons/suites_icon.svg?react';
import executionsIcon from '../../assets/icons/executions_icon.svg?react';
import ImportIcon from '../../assets/icons/import_icon.svg?react';
import Settings from '../../assets/icons/settings.svg?react';
import UnfollowIcon from '../../assets/icons/unfollow_icon.svg?react';
import ExternalUser from '../../assets/icons/external_user.svg?react';
import SingleUser from '../../assets/icons/single_user.svg?react';
import GroupUser from '../../assets/icons/group_user.svg?react';
import TestFreshersLogo from '../../assets/icons/test_freshers_logo.svg?react';
import Azure from '../../assets/icons/azure.svg?react';
import Bitbucket from '../../assets/icons/bitbucket.svg?react';
import Github from '../../assets/icons/github.svg?react';
import Gitlab from '../../assets/icons/gitlab.svg?react';
import Jenkins from '../../assets/icons/jenkins.svg?react';
import JiraLogo from '../../assets/icons/jira_logo.svg?react';
import Slack from '../../assets/icons/slack.svg?react';
import DisableIcon from '../../assets/icons/disable_icon.svg?react';
import DisableIconFilled from '../../assets/icons/disable_icon_filled.svg?react';
import EnableIcon from '../../assets/icons/enable_icon.svg?react';
import EnableIconFilled from '../../assets/icons/enable_icon_filled.svg?react';

import ClearHistory from '../../assets/icons/clear_history.svg?react';
import Capture from '../../assets/icons/capture.svg?react';
import Csharp from '../../assets/icons/csharp.svg?react';
import Cypress from '../../assets/icons/cypress.svg?react';
import Java from '../../assets/icons/java.svg?react';
import JavaScript from '../../assets/icons/javascript.svg?react';
import PlayWright from '../../assets/icons/playwright.svg?react';
import Python from '../../assets/icons/python.svg?react';
import Code from '../../assets/icons/code.svg?react';
import Regenerate from '../../assets/icons/regenerate.svg?react';
import Mic from '../../assets/icons/mic.svg?react';
import MicActive from '../../assets/icons/mic_filled.svg?react';
import RightArrowFilled from '../../assets/icons/right_arrow_filled_icon.svg?react';
import CodeColored from '../../assets/icons/code_colored.svg?react';
import DesignLink from '../../assets/icons/design_link.svg?react';
import FileColored from '../../assets/icons/file_colored.svg?react';
import JiraColored from '../../assets/icons/jira_colored.svg?react';
import Screenshot from '../../assets/icons/screenshot.svg?react';
import DeleteFilled from '../../assets/icons/delete_filled.svg?react';
import PrimaryCalendarIcon from '../../assets/icons/primary_calendar_icon.svg?react';
import SauseLabPrimaryIcon from '../../assets/icons/sause_lab_icon.svg?react';
import ModuleIcon from '../../assets/icons/module_icon.svg?react';

import totalDefectsStatusIcon from '../../assets/icons/total_defects_status_icon.svg?react';
import openDefectsStatusIcon from '../../assets/icons/open_defects_icon.svg?react';
import closedDefectsStatusIcon from '../../assets/icons/close_defects_icon.svg?react';
import qualityScoreStatusIcon from '../../assets/icons/quality_score_icon.svg?react';
import defectDensityStatusIcon from '../../assets/icons/defect_density_icon.svg?react';

import Private from '../../assets/icons/private.svg?react';
import Reschedule from '../../assets/icons/reschedule.svg?react';
import CollapseAllIcon from '../../assets/icons/collapse_icon.svg?react';
import ExpandAllIcon from '../../assets/icons/expand_icon.svg?react';
import DownArrow from '../../assets/icons/down_arrow.svg?react';
import UpArrow from '../../assets/icons/up_arrow.svg?react';
import LocatorIcon from '../../assets/icons/locator_icon.svg?react';
import AutomaticLocator from '../../assets/icons/automatic_locator.svg?react';
import ReRunFailedOnly from '../../assets/icons/re_run_failed_only.svg?react';
import ReRun from '../../assets/icons/re_run.svg?react';
import ShowAllExpand from '../../assets/icons/show_all_expand.svg?react';
import ShowAllCollapse from '../../assets/icons/show_all_collapse.svg?react';
import OverView from '../../assets/icons/overview.svg?react';
import CreateIssue from '../../assets/icons/create_issue.svg?react';
import ShowScripts from '../../assets/icons/show_scripts.svg?react';
import HideScripts from '../../assets/icons/hide_scripts.svg?react';
import FiaIcon from '../../assets/icons/fia_icon.svg?react';
import ArrowLeft from '../../assets/icons/arrow_left.svg?react';
import AccordionBack from '../../assets/icons/accordion_back.svg?react';
import LinkIcon from '../../assets/icons/link.svg?react';
import ArrowLeftAccordian from '../../assets/icons/arrow_left_accordian.svg?react';
import ArrowRightIcon from '../../assets/icons/arrow_right_icon.svg?react';
import DiscardAlert from '../../assets/icons/discard_alert.svg?react';
import ActiveAISearchIcon from '../../assets/icons/ai_search_active_icon.svg?react';
import DefaultAISearchIcon from '../../assets/icons/ai_search_default_icon.svg?react';
import Attachments from '../../assets/icons/attachments.svg?react';
import AttachLink from '../../assets/icons/attach_link.svg?react';
import Comments from '../../assets/icons/comments.svg?react';
import FileDownload from '../../assets/icons/file_download.svg?react';
import UploadFile from '../../assets/icons/upload_file.svg?react';
import TagIcon from '../../assets/icons/tag_icon.svg?react';
import AnalyticsIcon from '../../assets/icons/analytics_icon.svg?react';
import BuildingBlocksIcon from '../../assets/icons/building_blocks_icon.svg?react';
import ClientIcon from '../../assets/icons/client_icon.svg?react';
import InputIcon from '../../assets/icons/input_icon.svg?react';
import NlpIcon from '../../assets/icons/nlp_icon.svg?react';
import OutputIcon from '../../assets/icons/output_icon.svg?react';
import PendingRequestIcon from '../../assets/icons/pending_request_icon.svg?react';
import PrerequisitesIcon from '../../assets/icons/prerequisites_icon.svg?react';
import ProcedureIcon from '../../assets/icons/procedure_icon.svg?react';
import ProgramElementsIcon from '../../assets/icons/program_elements_icon.svg?react';
import ProjectConfigurationIcon from '../../assets/icons/project_configuration_icon.svg?react';
import RelatedNlpIcon from '../../assets/icons/related_nlp_icon.svg?react';
import ScenariosIcon from '../../assets/icons/scenarios_icon.svg?react';
import RequestIcon from '../../assets/icons/request_icon.svg?react';
import FillFilter from '../../assets/icons/fill_filter.svg?react';
import StatusFillFilterIcon from '../../assets/icons/status_fill_filter_icon.svg?react';
import PlayButton from '../../assets/icons/play_button.svg?react';
import PauseButton from '../../assets/icons/pause_button.svg?react';

import AskFiaIcon from '../../assets/icons/ask_fia_icon.svg?react';
import CommentIcon from '../../assets/icons/comment.svg?react';
import CollapseArrow from '../../assets/icons/collapse_arrow.svg?react';
import ExpandArrow from '../../assets/icons/expand_arrow.svg?react';
import AiTag from '../../assets/icons/ai_tag.svg?react';
import ManualTag from '../../assets/icons/manual_tag.svg?react';
import Createtag from '../../assets/icons/create_tag.svg?react';
import TagList from '../../assets/icons/tag_list.svg?react';
import CodeIcon from '../../assets/icons/code_icon.svg?react';
import DesignIcon from '../../assets/icons/designlink_icon.svg?react';
import ScreenshotIcon from '../../assets/icons/screenshot_icon.svg?react';
import LanguageIcon from '../../assets/icons/language_icon.svg?react';
import UploadProfileImage from '../../assets/icons/upload_profile_image.svg?react';
import globeIcon from '../../assets/icons/globe.svg?react';
import sequentialInfoIcon from '../../assets/icons/sequential_info.svg?react';
import parallelInfoIcon from '../../assets/icons/parallel_info.svg?react';
import distributeInfoIcon from '../../assets/icons/distriburte_info.svg?react';

import execution from '../../assets/icons/execution.svg?react';
import liveExecution from '../../assets/icons/live_execution.svg?react';
import hidePrePostCondition from '../../assets/icons/hide_pre_post_condition.svg?react';
import showPrePostCondition from '../../assets/icons/show_pre_post_condition.svg?react';
import showScript from '../../assets/icons/show_script.svg?react';
import hideScript from '../../assets/icons/hide_script.svg?react';
import replyComment from '../../assets/icons/comment_reply.svg?react';
import Terminated from '../../assets/icons/terminated.svg?react';
import Revert from '../../assets/icons/revert.svg?react';
import QuickRunSettingActive from '../../assets/icons/quick_run_setting_active.svg?react';
import RunManualTestcaseActive from '../../assets/icons/run_manual_testcase_active.svg?react';
import VideoPlayIcon from '../../assets/icons/video_play_icon.svg?react';
import TickIcon from '../../assets/icons/tick_icon.svg?react';
import Postman from '../../assets/icons/postman_icon.svg?react';
import RecordPlayback from '../../assets/icons/record_play.svg?react';
import NoContent from '../../assets/icons/no_content_icon.svg?react';
import CommonNlp from '../../assets/icons/common_nlp.svg?react';
import GenericNlp from '../../assets/icons/generic_nlp.svg?react';
import ExportPostman1 from '../../assets/icons/export_postman1.svg?react';
import ExportGlobalPostman from '../../assets/icons/export_global_postman.svg?react';
import ExportPEVPostman from '../../assets/icons/export_pev_postman.svg?react';
import OptimizeStepGroup from '../../assets/icons/optimize_stepgroup.svg?react';
import CircleCheckIcon from '../../assets/icons/circle-check-icon.svg?react';
import SquareCheckIcon from '../../assets/icons/square-check-icon.svg?react';
import AddScriptIcon from '../../assets/icons/add_script.svg?react';
import SuggestionToFix from '../../assets/icons/suggestion_to_fix.svg?react';
import GotoScript from '../../assets/icons/go_to_scripts.svg?react';
import SettingIcon from '../../assets/icons/setting-icon.svg?react';
import SeleniumIcon from '../../assets/icons/selenium_icon.svg?react';
import DeletePopUpIcon from '../../assets/icons/delete_popup_icon.svg?react';
import VideoPreviewIcon from '../../assets/icons/video_preview_icon.svg?react';
import FilterActive from '../../assets/icons/Filter_active.svg?react';
import MaximizedNewIcon from '../../assets/icons/maximize_new_icon.svg?react';
import AutoHealing from '../../assets/icons/auto_healing.svg?react';
import ClockFilled from '../../assets/icons/clock_filled.svg?react';
import EditLabelCloseIcon from '../../assets/icons/toast_close.svg?react';
import DrawerIconClose from '../../assets/icons/drawer_close_icon.svg?react';
import SendReport from '../../assets/icons/send_report.svg?react';
import ClosePillFilled from '../../assets/icons/close_pill_fill.svg?react';
import AppActions from '../../assets/icons/app_actions_icon.svg?react';
import SessionSetting from '../../assets/icons/session_setting_icon.svg?react';
import TestGallary from '../../assets/icons/test_gallary_icon.svg?react';
import Resolution from '../../assets/icons/resolution_icon.svg?react';
import VideoRecordIcon from '../../assets/icons/video_record_icon.svg?react';
import Delete from '../../assets/icons/delete_icon.svg?react';
import AiApprovedAutomark from '../../assets/icons/ai_approved.svg?react';
import videoliveicon from '../../assets/icons/Video_recording.svg?react';
import CaptureIconImage from '../../assets/icons/capture_image.svg?react';
import EclipsePluginIcon from '../../assets/icons/eclipse_plugin.svg?react';
import AiToken from '../../assets/icons/ai_token.svg?react';
import CloudClock from '../../assets/icons/cloud_clock.svg?react';
import ScreenExpand from '../../assets/icons/screen_expand_icon.svg?react';
import ScreenShotCapture from '../../assets/icons/screenshot_capture_icon.svg?react';
import SamsungIcon from '../../assets/icons/samsung_icon.svg?react';
import GoogleIcon from '../../assets/icons/google_icon.svg?react';
import OnePlusIcon from '../../assets/icons/oneplus_icon.svg?react';
import XiaomiIcon from '../../assets/icons/xiaomi_icon.svg?react';
import HuaweiIcon from '../../assets/icons/huawei_icon.svg?react';
import AmazonIcon from '../../assets/icons/amazon_icon.svg?react';
import ScriptsIcon from '../../assets/icons/scripts.svg?react';
import DialogInfoIcon from '../../assets/icons/dialog_info.svg?react';
import RecordPauseIcon from '../../assets/icons/record_pause_icon.svg?react'
import RecordStopIcon from '../../assets/icons/record_stop_icon.svg?react'
import AddSettings from '../../assets/icons/add_setting.svg?react'

Components['success'] = ToastSuccessIcon;
Components['setting_icon'] = SettingIcon;
Components['alert'] = Alert;
Components['alert'] = Alert;
Components['delete_info'] = DeleteInfoIcon;
Components['delete_popup_icon'] = DeletePopUpIcon;
Components['warning'] = WarningIcon;
Components['toast_info'] = ToastInfoIcon;
Components['error'] = ToastErrorIcon;
Components['close'] = ToastCloseIcon;
Components['more'] = MoreIcon;
Components['logo'] = Logo;
Components['manage_apps'] = ManageApps;
Components['arrow_up'] = ArrowUp;
Components['accordion_header_icon'] = AccordionHeaderIcon;
Components['dropzone_icon'] = DropZoneIcon;
Components['file'] = File;
Components['replace'] = Replace;
Components['remove'] = Remove;
Components['plus_icon'] = PlusIcon;
Components['arrows_top_icon'] = ArrowsTopIcon;
Components['arrows_right_icon'] = ArrowsRightIcon;
Components['arrows_down_icon'] = ArrowsDownIcon;
Components['arrow_down'] = ArrowDown;
Components['close_pill'] = ClosePill;
Components['moon_stars_icon'] = MoonStarsIcon;
Components['sun_icon'] = SunIcon;
Components['check_mark'] = CheckMarkIcon;
Components['wrong_mark'] = WrongMarkIcon;
Components['fireflink_icon'] = FireflinkIcon;
Components['tick'] = Tick;
Components['arrow_right'] = ArrowRight;
Components['search'] = Search;
Components['filter'] = Filter;
Components['right_arrow_icon'] = RightArrow;
Components['left_arrow_icon'] = LeftArrow;
Components['clock_icon'] = ClockIcon;
Components['edit'] = Edit;
Components['view_icon'] = ViewIcon;
Components['export_collection'] = ExportCollection;
Components['run_icon'] = RunIcon;
Components['license'] = LicenseIcon;
Components['delete'] = DeleteIcon;
Components['details'] = DetailsIcon;
Components['impact_list'] = ImpactListIcon;
Components['beautify_icon'] = BeautifyIcon;
Components['add_variable_icon'] = AddVariable;
Components['replace_file'] = ReplaceFile;
Components['formate_painter'] = FormatePainter;
Components['bold'] = Bold;
Components['italic'] = Italic;
Components['strike_through'] = StrikeThrough;
Components['underline'] = Underline;
Components['double_underline'] = DoubleUnderline;
Components['border_left'] = BorderLeft;
Components['border_right'] = BorderRight;
Components['border_bottom'] = BorderBottom;
Components['border_top'] = BorderTop;
Components['all_borders'] = AllBorders;
Components['no_border'] = NoBorder;
Components['text_align_center'] = TextAlignCenter;
Components['text_align_left'] = TextAlignLeft;
Components['text_align_right'] = TextAlignRight;
Components['text_color'] = TextColor;
Components['fill_color'] = FillColor;
Components['formula_icon'] = FormulaIcon;
Components['excel_corner_menu'] = ExcelCornerMenu;
Components['auto_save_icon'] = AutoSaveIcon;
Components['export'] = Export;
Components['import_file'] = ImportFile;
Components['apk_file_type'] = ApkFileType;
Components['csv_file_type'] = CsvFileType;
Components['compressed_file_type'] = CompressedFileType;
Components['html_file_type'] = HtmlFileType;
Components['json_file_type'] = JsonFileType;
Components['pdf_file_type'] = PdfFileType;
Components['png_file_type'] = PngFileType;
Components['xlsx_file_type'] = XlsxFileType;
Components['xml_file_type'] = XmlFileType;
Components['xls_file_type'] = XlsFileType;
Components['ipk_file_type'] = IpkFileType;
Components['txt_file_type'] = TxtFileType;
Components['gif_file_type'] = GifFileType;
Components['jpg_file_type'] = JpgFileType;
Components['doc_file_type'] = DocFileType;
Components['docx_file_type'] = DocxFileType;
Components['ipa_file_type'] = IpaFileType;
Components['jpeg_file_type'] = JpegFileType;
Components['js_file_type'] = JsFileType;
Components['md_file_type'] = MdFileType;
Components['mp3_file_type'] = Mp3FileType;
Components['mp4_file_type'] = Mp4FileType;
Components['pdfx_file_type'] = PdfxFileType;
Components['pem_file_type'] = PemFileType;
Components['ppt_file_type'] = PptFileType;
Components['pptx_file_type'] = PptxFileType;
Components['svg_file_type'] = SvgFileType;
Components['w_file_type'] = WFileType;
Components['wav_file_type'] = WavFileType;
Components['y4m_file_type'] = Y4mFileType;
Components['yml_file_type'] = YmlFileType;
Components['bin_file_type'] = BinFileType;
Components['m4v_file_type'] = M4vFileType;
Components['mov_file_type'] = MovFileType;
Components['pfx_file_type'] = PfxFileType;

Components['import'] = Import;
Components['info'] = InfoIcon;
Components['calendar_icon'] = CalendarIcon;
Components['hide_icon'] = HideIcon;
Components['vertical_separator'] = VerticalSeparator;
Components['collapse_icon'] = CollapseIcon;
Components['refresh_icon'] = RefreshIcon;
Components['download_file'] = DownloadFile;
Components['copy_icon'] = CopyIcon;
Components['expand_icon'] = ExpandIcon;
Components['license_info'] = LicenseInfo;
Components['license_warning'] = LicenseWarning;
Components['variable_icon'] = VariableIcon;
Components['download_icon'] = DownloadIcon;
Components['web_icon'] = WebIcon;
Components['web&mobile_icon'] = WebMobileIcon;
Components['mobile_icon'] = MobileIcon;
Components['sales_force'] = SalesForceIcon;
Components['ms_dynamic'] = MSDynamicIcon;
Components['all_projects'] = AllProjectsIcon;
Components['android_icon'] = AndroidIcon;
Components['plus_user_icon'] = PlusUserIcon;
Components['label_plus'] = LabelPlusIcon;
Components['manual_locator'] = ManualLocator;
Components['ios_icon'] = IosIcon;
Components['help_icon'] = HelpIcon;
Components['select_license'] = SwitchLicenseIcon;
Components['fireflink-logo'] = FireflinkLogo;
Components['wswb_delete_icon'] = WSWBDeleteIcon;
Components['wswb_plus_icon'] = WSWBPlusIcon;
Components['local_variable_icon'] = LocalVariableIcon;
Components['global_variable_icon'] = GlobalVariableIcon;
Components['project_env_variable_icon'] = ProjectEnvVariableIcon;
Components['step_group_parameter'] = StepGroupParameterIcon;
Components['step_group_variable'] = StepGroupVariableIcon;
Components['data_provider_variable'] = DataProviderVariableIcon;
Components['for_loop_variable'] = ForLoopVariableIcon;
Components['add_locator'] = AddLocator;
Components['drag'] = Drag;
Components['windows'] = Windows;
Components['datalist_icon'] = DataListIcon;
Components['mac_icon'] = Mac;
Components['android_icon'] = Android;
Components['chrome_icon'] = Chrome;
Components['browser_stack_icon'] = BrowserStack;
Components['run_icon'] = Run;
Components['backward_icon'] = BackwardIcon;
Components['forward_icon'] = ForwardIcon;
Components['reload'] = Reload;
Components['window_maximize'] = WindowMaximize;
Components['window_restore'] = WindowRestore;
Components['window_minimize'] = WindowMinimize;
Components['hamburger_menu'] = HamburgerMenu;
Components['app_switch'] = AppSwitchIcon;
Components['user_profile'] = UserProfile;
Components['continue_without_signin'] = ContinueSignIn;
Components['cloud_server_host'] = CloudServerHost;
Components['notification_icon'] = NotificationIcon;
Components['nlp_help_icon'] = NLPHelpIcon;
Components['update_icon'] = UpdateIcon;
Components['add_file'] = AddFile;
Components['add_new_file'] = AddNewFile;
Components['plus_round_icon'] = PlusRoundIcon;
Components['clone_icon'] = CloneIcon;
Components['move_icon'] = MoveIcon;
Components['jira'] = Jira;
Components['history'] = HistoryIcon;
Components['linked_defects'] = LinkedDefects;
Components['no_access_icon'] = NoAccessIcon;
Components['full_access_icon'] = FullAccessIcon;
Components['view_access_icon'] = ViewAccessIcon;
Components['hide_access_icon'] = HideAccessIcon;
Components['eye_closed'] = EyeClosed;
Components['attachment_icon'] = AttachmentIcon;
Components['authorization_icon'] = AuthorizationIcon;
Components['ai_search'] = AiSearch;
Components['upload_pill'] = UploadPillIcon;
Components['add_from_shared_element'] = AddFromSharedElement;
Components['fireflink_platform_logo'] = FireflinkPlatform;
Components['fireflink_finder_logo'] = FireflinkFinder;
Components['client_profile'] = ClientProfile;
Components['license_expired'] = LicenseExpired;
Components['dashboard_web_icon'] = dashboardWebIcon;
Components['dashboard_mobile_icon'] = dashboardMobileIcon;
Components['dashboard_web_mobile_icon'] = dashboardWebMobileIcon;
Components['dashboard_web_services'] = dashboardWebServicesIcon;
Components['dashboard_salesforce_icon'] = dashboardSalesforceIcon;
Components['dashboard_ms_dynamic_icon'] = dashboardMsDynamicIcon;
Components['add_testcase'] = AddTestCaseIcon;
Components['automation_testcase'] = AutomationTestCaseIcon;
Components['manual_testcase'] = ManualTestCaseIcon;
Components['back_icon'] = BackIcon;
Components['sause_lab'] = SauseLabIcon;
Components['local'] = LocalIcon;
Components['internet_explorer'] = InternetExplorerIcon;
Components['browserstack_icon'] = BrowserstackIcon;
Components['edge'] = EdgeIcon;
Components['fire_fox'] = FirefoxIcon;
Components['lambda_icon'] = LambdaIcon;
Components['linux'] = LinuxIcon;
Components['opera'] = OperaIcon;
Components['safari_icon'] = SafariIcon;
Components['maximize_script'] = MaximizeScript;
Components['download_file_icon'] = DownloadFileIcon;
Components['maximize_icon'] = MaximizeIcon;
Components['passed_status_icon'] = PassedStatusIcon;
Components['failed_status_icon'] = FailedStatusIcon;
Components['warning_status_icon'] = WarningStatusIcon;
Components['skipped_status_icon'] = SkippedStatusIcon;
Components['flaky_status_icon'] = FlakyStatusIcon;
Components['drawer_maximize'] = DrawerMaximizeIcon;
Components['save_as_step'] = SaveAsStepIcon;
Components['send_to_steps'] = SendToStepsIcon;
Components['standard_template'] = StandardTemplate;
Components['sample_template_first'] = SampleTemplateFirst;
Components['sample_template_second'] = SampleTemplateSecond;
Components['no_license_found'] = NoLicenseFound;
Components['data_provider'] = DataProvider;
Components['link_expired'] = LinkExpired;
Components['link_reset'] = LinkReset;
Components['system_warning'] = SystemWarning;
Components['user_password_lock'] = UserPasswordLock;
Components['user_warning'] = UserWarning;
Components['user_with_system'] = UserWithSystem;
Components['minimize_script'] = MinimizeScript;
Components['maximize_tree'] = MaximizeTree;
Components['label_icon'] = LabelIcon;
Components['add_label_icon'] = AddLabelIcon;
Components['quick_run_setting'] = QuickRunSettingIcon;
Components['run_manual_testcase'] = RunManualTestcaseIcon;
Components['run_automation_scripts'] = RunAutomationScriptsIcon;
Components['eye_open_icon'] = EyeOpenIcon;
Components['replace_icon'] = ReplaceIcon;
Components['header_preset'] = HeaderPreset;
Components['project_element'] = ProjectElement;
Components['element'] = Element;
Components['step_group'] = StepGroup;
Components['variable'] = Variable;
Components['defects'] = Defects;
Components['approval_pending'] = ApprovalPending;
Components['configuration'] = Configuration;
Components['no_data'] = NoData;
Components['add_user'] = AddUser;
Components['add_to_archive'] = AddToArchive;
Components['remove_user'] = RemoveUser;
Components['add_variable'] = AddVariableIcon;
Components['dashboard_icon'] = DashboardIcon; //TODO:this is temporary icon
Components['info_user'] = InfoUser;
Components['web_service_icon'] = WebServiceIcon;
Components['project_status_icon'] = ProjectStatusIcon;
Components['capture_icon'] = captureIcon;
Components['backward'] = backward;
Components['forward'] = forward;
Components['refresh_icon'] = refreshIcon;
Components['rotate_icon'] = rotateIcon;
Components['tap_icon'] = tapIcon;
Components['swipe_icon'] = swipeIcon;
Components['depends_on_script'] = dependsOnScript;
Components['parameters'] = parameters;
Components['pre_post_condition'] = prePostCondition;
Components['program_element'] = programElement;
Components['test_data'] = testData;
Components['test_data_set'] = testDataSet;
Components['email_group'] = emailGroup;
Components['variable_set'] = variableSet;
Components['machine_enable_icon'] = machineEnableIcon;
Components['machine_disable_icon'] = machineDisableIcon;
Components['executions_icon'] = executionsIcon;
Components['suites_icon'] = suitesIcon;
Components['import_icon'] = ImportIcon;
Components['settings'] = Settings;
Components['test_freshers_logo'] = TestFreshersLogo;
Components['unfollow_icon'] = UnfollowIcon;
Components['external_user'] = ExternalUser;
Components['single_user'] = SingleUser;
Components['group_user'] = GroupUser;
Components['azure'] = Azure;
Components['bitbucket'] = Bitbucket;
Components['github'] = Github;
Components['gitlab'] = Gitlab;
Components['jenkins'] = Jenkins;
Components['jira_logo'] = JiraLogo;
Components['slack'] = Slack;
Components['disable_icon'] = DisableIcon;
Components['enable_icon'] = EnableIcon;
Components['clear_history'] = ClearHistory;
Components['capture'] = Capture;
Components['csharp'] = Csharp;
Components['cypress'] = Cypress;
Components['java'] = Java;
Components['javascript'] = JavaScript;
Components['playwright'] = PlayWright;
Components['python'] = Python;
Components['code'] = Code;
Components['regenerate'] = Regenerate;
Components['mic'] = Mic;
Components['mic_filled'] = MicActive;
Components['right_arrow_filled_icon'] = RightArrowFilled;
Components['code_colored'] = CodeColored;
Components['design_link'] = DesignLink;
Components['file_colored'] = FileColored;
Components['jira_colored'] = JiraColored;
Components['screenshot'] = Screenshot;
Components['delete_filled'] = DeleteFilled;
Components['primary_calendar_icon'] = PrimaryCalendarIcon;
Components['sause_lab_icon'] = SauseLabPrimaryIcon;
Components['fire_flink_loader_logo'] = FireFlinkLoaderLogo;
Components['line_loader'] = LoaderSvg;

Components['total_defects_status_icon'] = totalDefectsStatusIcon;
Components['open_defects_status_icon'] = openDefectsStatusIcon;
Components['closed_defects_status_icon'] = closedDefectsStatusIcon;
Components['quality_score_status_icon'] = qualityScoreStatusIcon;
Components['defect_density_status_icon'] = defectDensityStatusIcon;
Components['module_icon'] = ModuleIcon;

Components['private'] = Private;
Components['reschedule'] = Reschedule;
Components['collapseAll_icon'] = CollapseAllIcon;
Components['expandAll_icon'] = ExpandAllIcon;
Components['down_arrow'] = DownArrow;
Components['up_arrow'] = UpArrow;
Components['locator_icon'] = LocatorIcon;
Components['automatic_locator'] = AutomaticLocator;
Components['re_run_failed_only'] = ReRunFailedOnly;
Components['re_run'] = ReRun;
Components['show_all_expand'] = ShowAllExpand;
Components['show_all_collapse'] = ShowAllCollapse;
Components['overview'] = OverView;
Components['create_issue'] = CreateIssue;
Components['show_scripts'] = ShowScripts;
Components['hide_scripts'] = HideScripts;
Components['link'] = LinkIcon;
Components['arrow_left'] = ArrowLeft;
Components['accordion_back'] = AccordionBack;
Components['fia_icon'] = FiaIcon;
Components['record_pause_icon'] = RecordPauseIcon
Components['record_stop_icon'] = RecordStopIcon
Components['add_setting'] = AddSettings

Components['arrow_left_accordian'] = ArrowLeftAccordian;
Components['arrow_right_icon'] = ArrowRightIcon;
Components['discard_alert'] = DiscardAlert;
Components['ai_search_default_icon'] = DefaultAISearchIcon;
Components['ai_search_active_icon'] = ActiveAISearchIcon;

Components['attachments'] = Attachments;
Components['attach_link'] = AttachLink;
Components['comments'] = Comments;
Components['file_download'] = FileDownload;
Components['upload_file'] = UploadFile;

Components['tag_icon'] = TagIcon;
Components['analytics_icon'] = AnalyticsIcon;
Components['building_blocks_icon'] = BuildingBlocksIcon;
Components['client_icon'] = ClientIcon;
Components['input_icon'] = InputIcon;
Components['nlp_icon'] = NlpIcon;
Components['output_icon'] = OutputIcon;
Components['pending_request_icon'] = PendingRequestIcon;
Components['prerequisites_icon'] = PrerequisitesIcon;
Components['procedure_icon'] = ProcedureIcon;
Components['program_elements_icon'] = ProgramElementsIcon;
Components['project_configuration_icon'] = ProjectConfigurationIcon;
Components['related_nlp_icon'] = RelatedNlpIcon;
Components['scenarios_icon'] = ScenariosIcon;
Components['request_icon'] = RequestIcon;
Components['fill_filter'] = FillFilter;
Components['status_fill_filter_icon'] = StatusFillFilterIcon;
Components['play_button'] = PlayButton;
Components['pause_button'] = PauseButton;
Components['ask_fia_icon'] = AskFiaIcon;
Components['comment_icon'] = CommentIcon;
Components['expand-arrow'] = ExpandArrow;
Components['collapse-arrow'] = CollapseArrow;
Components['ai_tag'] = AiTag;
Components['manual_tag'] = ManualTag;
Components['create_tag'] = Createtag;
Components['tag_list'] = TagList;
Components['code_icon'] = CodeIcon;
Components['designlink_icon'] = DesignIcon;
Components['screenshot_icon'] = ScreenshotIcon;
Components['language_icon'] = LanguageIcon;
Components['upload_profile_image'] = UploadProfileImage;
Components['globe_icon'] = globeIcon;
Components['sequential_info_icon'] = sequentialInfoIcon;
Components['parallel_info_icon'] = parallelInfoIcon;
Components['distribute_info_icon'] = distributeInfoIcon;

Components['execution'] = execution;
Components['live_execution'] = liveExecution;
Components['hide_pre_post_condition'] = hidePrePostCondition;
Components['show_pre_post_condition'] = showPrePostCondition;
Components['show_script'] = showScript;
Components['hide_script'] = hideScript;
Components['comment_reply'] = replyComment;
Components['terminated'] = Terminated;
Components['revert'] = Revert;
Components['quick_run_setting_active'] = QuickRunSettingActive;
Components['run_manual_testcase_active'] = RunManualTestcaseActive;
Components['video_play_icon'] = VideoPlayIcon;
Components['tick_icon'] = TickIcon;
Components['postman_icon'] = Postman;
Components['record_play'] = RecordPlayback;
Components['no_content'] = NoContent;
Components['common_nlp'] = CommonNlp;
Components['generic_nlp'] = GenericNlp;
Components['export_postman1'] = ExportPostman1;
Components['export_global_postman'] = ExportGlobalPostman;
Components['export_pev_postman'] = ExportPEVPostman;
Components['optimize_stepgroup'] = OptimizeStepGroup;

Components['circle_check_icon'] = CircleCheckIcon;
Components['square_check_icon'] = SquareCheckIcon;
Components['add_script'] = AddScriptIcon;
Components['suggestion_to_fix'] = SuggestionToFix;
Components['go_to_script'] = GotoScript;
Components['selenium_icon'] = SeleniumIcon;
Components['video_preview'] = VideoPreviewIcon;
Components['filter_active'] = FilterActive;
Components['auto_healing'] = AutoHealing;

Components['maximize_new_icon'] = MaximizedNewIcon;
Components['left_new_icon'] = LeftNewIcon;
Components['right_new-icon'] = RightNewIcon;
Components['clock_filled'] = ClockFilled;
Components['maximize_new'] = MaximizedNewIcon;
Components['left_new_icon'] = LeftNewIcon;
Components['right_new_icon'] = RightNewIcon;
Components['edit_label_close'] = EditLabelCloseIcon;
Components['drawer_icon_close'] = DrawerIconClose;
Components['send_report'] = SendReport;
Components['close_pill_fill'] = ClosePillFilled;
Components['app_actions_icon'] = AppActions;
Components['session_setting_icon'] = SessionSetting;
Components['test_gallary_icon'] = TestGallary;
Components['resolution_icon'] = Resolution;
Components['video_record_icon'] = VideoRecordIcon;
Components['delete_icon'] = Delete;

Components['enable_filled'] = EnableIconFilled;
Components['disable_filled'] = DisableIconFilled;
Components['ai_approved'] = AiApprovedAutomark;
Components['video_live_icon'] = videoliveicon;
Components['screen_capture_icon'] = CaptureIconImage;
Components['eclipse_plugin'] = EclipsePluginIcon;
Components['ai_token'] = AiToken;
Components['cloud_clock'] = CloudClock;
Components['screen_expand_icon'] = ScreenExpand;
Components['screenshot_capture_icon'] = ScreenShotCapture;
Components['samsung_icon'] = SamsungIcon;
Components['google_icon'] = GoogleIcon;
Components['oneplus_icon'] = OnePlusIcon;
Components['xiaomi_icon'] = XiaomiIcon;
Components['huawei_icon'] = HuaweiIcon;
Components['amazon_icon'] = AmazonIcon;
Components['scripts'] = ScriptsIcon;
Components['dialog_info'] = DialogInfoIcon;

export default Components;
