let Components: any = {};

import ManageApps from '../../assets/Icons/manage_apps.svg?react';
import Logo from '../../assets/icons/logo.svg?react';
import ArrowUp from '../../assets/icons/arrow_up.svg?react';
import ArrowRight from '../../assets/icons/arrow_right.svg?react';
import AccordionHeaderIcon from '../../assets/icons/accordion_header_icon.svg?react';
import DeleteInfoIcon from '../../assets/icons/delete_info.svg?react';
import WarningIcon from '../../assets/icons/warning.svg?react';
import ToastInfoIcon from '../../assets/icons/info.svg?react';
import ToastErrorIcon from '../../assets/icons/error.svg?react';
import ToastCloseIcon from '../../assets/icons/toast_close.svg?react';
import ToastSuccessIcon from '../../assets/icons/success.svg?react';
import MoreIcon from '../../assets/icons/more.svg?react';
import DropZoneIcon from '../../assets/icons/dropzone_icon.svg?react';
import File from '../../assets/icons/file.svg?react';
import Replace from '../../assets/icons/replace.svg?react';
import Remove from '../../assets/icons/remove.svg?react';
import PlusIcon from '../../assets/icons/plus_icon.svg?react';
import ArrowsTopIcon from '../../assets/icons/arrows_top_icon.svg?react';
import ArrowsRightIcon from '../../assets/icons/arrows_right_icon.svg?react';
import ArrowsDownIcon from '../../assets/icons/arrows_down_icon.svg?react'; // import ArrowUp from '../../assets/Icons/arrow_up.svg?react';
import ArrowDown from '../../assets/Icons/arrow_down.svg?react';
import ClosePill from '../../assets/Icons/close_pill.svg?react';
import MoonStarsIcon from '../../assets/icons/moon_stars.svg?react';
import SunIcon from '../../assets/icons/sun_icon.svg?react';
import CheckMarkIcon from '../../assets/icons/check_mark.svg?react';
import WrongMarkIcon from '../../assets/icons/wrong_mark.svg?react';
import FireflinkIcon from '../../assets/Icons/fireflink_icon.svg?react';
import Tick from '../../assets/Icons/tick_icon.svg?react';
import Search from '../../assets/icons/search.svg?react';
import Filter from '../../assets/icons/filter.svg?react';
import RightArrow from '../../assets/icons/right_arrow_icon.svg?react';
import LeftArrow from '../../assets/icons/left_arrow_icon.svg?react';
import ClockIcon from '../../assets/icons/clock_icon.svg?react';
import Edit from '../../assets/icons/edit_icon.svg?react';
import ViewIcon from '../../assets/icons/view_icon.svg?react';
import ExportCollection from '../../assets/icons/export_collection_icon.svg?react';
import RunIcon from '../../assets/icons/run_icon.svg?react';
import AddVariable from '../../assets/icons/add_variable_icon.svg?react';

import LicenseIcon from '../../assets/icons/active_license_icon.svg?react';
import DeleteIcon from '../../assets/icons/delete.svg?react';
import DetailsIcon from '../../assets/icons/details.svg?react';
import ImpactListIcon from '../../assets/icons/impactList.svg?react';
import InfoIcon from '../../assets/icons/info_icon.svg?react';
import CalendarIcon from '../../assets/icons/calendar_icon.svg?react';
import HideIcon from '../../assets/icons/hide_icon.svg?react';
import VerticalSeparator from '../../assets/icons/vertical_separator.svg?react';
import CollapseIcon from '../../assets/icons/collapse-icon.svg?react';
import ExpandIcon from '../../assets/icons/expand-icon.svg?react';
import CopyIcon from '../../assets/icons/copy-icon.svg?react';
import DownloadFile from '../../assets/icons/download-icon.svg?react';
import RefreshIcon from '../../assets/icons/refresh-icon.svg?react';
import LicenseInfo from '../../assets/icons/license_info.svg?react';
import LicenseWarning from '../../assets/icons/license_warning.svg?react';
import DownloadIcon from '../../assets/icons/download_icon.svg?react';
import WebIcon from '../../assets/icons/web_icon.svg?react';
import WebMobileIcon from '../../assets/icons/web&mobile_icon.svg?react';
import MobileIcon from '../../assets/icons/mobile_icon.svg?react';
import SalesForceIcon from '../../assets/icons/sales_force.svg?react';
import MSDynamicIcon from '../../assets/icons/ms_dynamic.svg?react';
import AllProjectsIcon from '../../assets/icons/all_projects.svg?react';
import AndroidIcon from '../../assets/icons/android_icon.svg?react';

import SwitchLicenseIcon from '../../assets/icons/switch_license_icon.svg?react';
import FireflinkLogo from '../../assets/icons/fireflink_logo.svg?react';
import WSWBDeleteIcon from '../../assets/icons/wswb_delete_icon.svg?react'
import WSWBPlusIcon from '../../assets/icons/wswb_plus_icon.svg?react'


//icons
Components['delete_info'] = DeleteInfoIcon;
Components['success'] = ToastSuccessIcon;
Components['warning'] = WarningIcon;
Components['toast_info'] = ToastInfoIcon;
Components['error'] = ToastErrorIcon;
Components['close'] = ToastCloseIcon;
Components['more'] = MoreIcon;
Components['logo'] = Logo;
Components['manage_apps'] = ManageApps;
Components['arrow_up'] = ArrowUp;
Components['accordion_header_icon'] = AccordionHeaderIcon;
Components['dropzone_icon'] = DropZoneIcon;
Components['file'] = File;
Components['replace'] = Replace;
Components['remove'] = Remove;
Components['plus_icon'] = PlusIcon;
Components['arrows_top_icon'] = ArrowsTopIcon;
Components['arrows_right_icon'] = ArrowsRightIcon;
Components['arrows_down_icon'] = ArrowsDownIcon;
Components['arrow_down'] = ArrowDown;
Components['close_pill'] = ClosePill;
Components['moon_stars_icon'] = MoonStarsIcon;
Components['sun_icon'] = SunIcon;
Components['check_mark'] = CheckMarkIcon;
Components['wrong_mark'] = WrongMarkIcon;
Components['fireflink_icon'] = FireflinkIcon;
Components['tick'] = Tick;
Components['arrow_right'] = ArrowRight;
Components['search'] = Search;
Components['filter'] = Filter;
Components['right_arrow_icon'] = RightArrow;
Components['left_arrow_icon'] = LeftArrow;
Components['clock_icon'] = ClockIcon;
Components['edit'] = Edit;
Components['view_icon'] = ViewIcon;
Components['export_collection'] = ExportCollection;
Components['run_icon'] = RunIcon;
Components['license'] = LicenseIcon;
Components['delete'] = DeleteIcon;
Components['details'] = DetailsIcon;
Components['impactList'] = ImpactListIcon;
Components['add_variable'] = AddVariable;
Components['info'] = InfoIcon;
Components['calendar_icon'] = CalendarIcon;
Components['hide_icon'] = HideIcon;
Components['vertical_separator'] = VerticalSeparator;
Components['collapse_icon'] = CollapseIcon;
Components['refresh_icon'] = RefreshIcon;
Components['download_file'] = DownloadFile;
Components['copy_icon'] = CopyIcon;
Components['expand_icon'] = ExpandIcon;
Components['license_info'] = LicenseInfo;
Components['license_warning'] = LicenseWarning;
Components['download_icon'] = DownloadIcon;
Components['web_icon'] = WebIcon;
Components['web&mobile_icon'] = WebMobileIcon;
Components['mobile_icon'] = MobileIcon;
Components['sales_force'] = SalesForceIcon;
Components['ms_dynamic'] = MSDynamicIcon;
Components['all_projects'] = AllProjectsIcon;
Components['android_icon'] = AndroidIcon;

Components['select_license'] = SwitchLicenseIcon;
Components['fireflink-logo'] = FireflinkLogo;
Components['wswb_delete_icon'] = WSWBDeleteIcon;
Components['wswb_plus_icon'] = WSWBPlusIcon;

export default Components;
