export const nlpList = [
  {
    desc: 'randomNumber',
    displayName: 'PostgreSQL : Update value *setValues* into *tableName* table',
    failMessage: 'randomNumber has failed',
    isNonPE: false,
    platform: 'Generic',
    name: 'randomNumber',
    nlpName: 'randomNumber',
    videoSrc: '',
    nlpType: 'NLP',
    packageName: 'com.tyss.optimize.programelement.LIC3813PJT1001.Logics',
    parentId: 'PKJ1017',
    passMessage: 'randomNumber has passed',
    programElementId: 'PRG_ELE1001',
    projectId: 'PJT1001',
    returnType: 'java.lang.Integer',
    searchName: 'randomNumber',
    stepInputs: [{}],
    toolTip: 'Logics : randomNumber',
    _class: 'com.tyss.optimize.data.models.db.model.ProgramElementNlp',
    _id: 'PE_NLPdbed27d0-b05a-4354-b9d3-c2f85307b4f2',
  },
  {
    desc: 'randomNumber',
    displayName: 'Wait for *element* until text contains *text*',
    platform: 'Android',

    failMessage: 'randomNumber has failed',
    isNonPE: false,
    name: 'randomNumber',
    nlpName: 'randomNumber',
    nlpType: 'PROGRAM_ELEMENTS',
    packageName: 'com.tyss.optimize.programelement.LIC3813PJT1001.Logics',
    parentId: 'PKJ1017',
    passMessage: 'randomNumber has passed',
    programElementId: 'PRG_ELE1001',
    projectId: 'PJT1001',
    returnType: 'java.lang.Integer',
    searchName: 'randomNumber',
    stepInputs: [{}],
    toolTip: 'Logics : randomNumber',
    _class: 'com.tyss.optimize.data.models.db.model.ProgramElementNlp',
    _id: 'PE_NLPdbed27d0-b05a-4354-b9d3-c2f85307b4f2',
  },
  {
    desc: 'randomNumber',
    platform: 'iOS',

    displayName:
      'String : Verify if string *string1* is equal to string *string2*',
    failMessage: 'randomNumber has failed',
    isNonPE: false,
    name: 'randomNumber',
    nlpName: 'randomNumber',
    nlpType: 'STEP_GROUP',
    packageName: 'com.tyss.optimize.programelement.LIC3813PJT1001.Logics',
    parentId: 'PKJ1017',
    passMessage: 'randomNumber has passed',
    programElementId: 'PRG_ELE1001',
    projectId: 'PJT1001',
    returnType: 'java.lang.Integer',
    searchName: 'randomNumber',
    stepInputs: [{}],
    toolTip: 'Logics : randomNumber',
    _class: 'com.tyss.optimize.data.models.db.model.ProgramElementNlp',
    _id: 'PE_NLPdbed27d0-b05a-4354-b9d3-c2f85307b4f2',
  },
  {
    desc: 'randomNumber',
    displayName:
      'Wait for page to load for maximum time limit of *time* second',
    failMessage: 'randomNumber has failed',
    isNonPE: false,
    platform: 'android',

    name: 'randomNumber',
    nlpName: 'randomNumber',
    nlpType: 'PROGRAM_ELEMENTS',
    packageName: 'com.tyss.optimize.programelement.LIC3813PJT1001.Logics',
    parentId: 'PKJ1017',
    passMessage: 'randomNumber has passed',
    programElementId: 'PRG_ELE1001',
    projectId: 'PJT1001',
    returnType: 'java.lang.Integer',
    searchName: 'randomNumber',
    stepInputs: [{ name: 'Range Of The Number', type: 'java.lang.Integer' }],
    toolTip: 'Logics : randomNumber',
    _class: 'com.tyss.optimize.data.models.db.model.ProgramElementNlp',
    _id: 'PE_NLPdbed27d0-b05a-4354-b9d3-c2f85307b4f2',
  },
  {
    description: '',
    displayName:
      'Excel : Get string cell data for given *uniqueData* and *header* for single row table',
    failMessage: 'Open Browser is failed',
    imported: false,
    libraryId: 'LIB1002',
    name: 'Open Browser',
    nlpName: 'Open Browser',
    nlpType: 'STEP_GROUP',
    parentId: 'STP_GRP1001',
    passMessage: 'Open Browser is passed',
    path: '/Root/Open and Close Browser/Open Browser',
    platform: 'Web',
    projectId: 'PJT1001',
    returnType: 'void',
    searchName: 'Open Browser',
    stepInputs: [],
    toolTip: 'Open and Close Browser : Open Browser : Web',
    _class: 'com.tyss.optimize.data.models.db.model.StepGroupNlp',
    _id: 'SG_NLP1001',
  },
  {
    desc: 'randomNumber',
    displayName: 'PostgreSQL : Update value *setValues* into *tableName* table',
    failMessage: 'randomNumber has failed',
    isNonPE: false,
    platform: 'Web',

    name: 'randomNumber',
    nlpName: 'randomNumber',
    nlpType: 'PROGRAM_ELEMENTS',
    packageName: 'com.tyss.optimize.programelement.LIC3813PJT1001.Logics',
    parentId: 'PKJ1017',
    passMessage: 'randomNumber has passed',
    programElementId: 'PRG_ELE1001',
    projectId: 'PJT1001',
    returnType: 'java.lang.Integer',
    searchName: 'randomNumber',
    stepInputs: [{}],
    toolTip: 'Logics : randomNumber',
    _class: 'com.tyss.optimize.data.models.db.model.ProgramElementNlp',
    _id: 'PE_NLPdbed27d0-b05a-4354-b9d3-c2f85307b4f2',
  },
  {
    desc: 'randomNumber',
    displayName: 'randomNumber',
    failMessage: 'randomNumber has failed',
    isNonPE: false,
    name: 'randomNumber',
    platform: 'Web',
    nlpName: 'randomNumber',
    nlpType: 'PROGRAM_ELEMENTS',
    packageName: 'com.tyss.optimize.programelement.LIC3813PJT1001.Logics',
    parentId: 'PKJ1017',
    passMessage: 'randomNumber has passed',
    programElementId: 'PRG_ELE1001',
    projectId: 'PJT1001',
    returnType: 'java.lang.Integer',
    searchName: 'randomNumber',
    stepInputs: [{}],
    toolTip: 'Logics : randomNumber',
    _class: 'com.tyss.optimize.data.models.db.model.ProgramElementNlp',
    _id: 'PE_NLPdbed27d0-b05a-4354-b9d3-c2f85307b4f2',
  },
  {
    nlpType: "PROGRAM_ELEMENTS",
    platform: "None",
    collectionName: "program_elements_nlps",
    score: "0",
    isNonPE: false,
    modifiedOn: "07 Apr 2025 02:54 PM",
    nlpName: "AddTwoNumbers",
    packageName: "com.tyss.optimize.programelement.LIC4088PJT1162.default_package",
    passMessage: "AddTwoNumbers has passed",
    toolTip: "default_package : AddTwoNumbers",
    programElementId: "PROGRAM_ELE_0000",
    failMessage: "AddTwoNumbers has failed",
    parentId: "PKJ1172",
    unique: "optimize_dev2_LIC4088PE_NLP144ad258-f170-4095-aa25-6450cffe2ab8",
    name: "AddTwoNumbers",
    projectId: "PJT1162",
    returnType: "java.lang.Integer",
    desc: "AddTwoNumbers",
    _id: "PE_NLP144ad258-f170-4095-aa25-6450cffe2ab8"
  }
];
export const filterSearchData = [
  { name: 'Navigate', isSelected: false },
  { name: 'Click', isSelected: false },
  { name: 'Enter', isSelected: false },
  { name: 'Wait', isSelected: false },
  { name: 'Navigate', isSelected: false },
  { name: 'Verify', isSelected: false },
  { name: 'Navigate', isSelected: false },
  { name: 'Get', isSelected: false },
  { name: 'Excel', isSelected: false },
  { name: 'Image', isSelected: false },
  { name: 'For Loop', isSelected: false },
  { name: 'Conditions', isSelected: false },
  { name: 'Database', isSelected: false },
  { name: 'Set', isSelected: false },
  { name: 'Iteration', isSelected: false },
];
